### ISSUE TITLE
Getting in water does drowning damage after a while

### ISSUE THREAD

**Issue by Fogrits** [Chainmail-Studios/Astromine#111]
The title explains itself
[Video if the title isn't explaining enough](https://youtu.be/lMKGxDe2yI4)

**Comment by Fogrits** [comment]
and due to this I can't explore underwater

**Comment by shedaniel** [comment]
thing bug is hilarious.

**Comment by vini2003** [comment]
I know why it's happening, will fix even though it's pretty comical lol

**Comment by vini2003** [comment]
Should be fixed in 1.0.9.

**Comment by vini2003** [comment]
My bad; 1.0.8.

**Comment by Fogrits** [comment]
thanks :)
