### ISSUE TITLE
Crash when using specific weapons on a dedicated server

### ISSUE THREAD

**Issue by JumboTSB** [Chainmail-Studios/Astromine#117]
Minecraft Version: 1.16.1
Fabric Version: 0.8.8
Fabric API Version: 0.14.0+build.371-1.16
Astromine Version: 1.0.10+fabric-1.16.1.jar

Details:
Apparently using weapons such as the barret on a dedicated server and the super slime shooter can cause fatal exceptions.

https://pastebin.com/NVcy3Lva

**Comment by vini2003** [comment]
Should be fixed, but I have not been able to test it yet.

**Comment by vini2003** [comment]
Fixed.
