### ISSUE TITLE
FoV mods (such as Ok Zoomer) incompatible

### ISSUE THREAD

**Issue by Linguardium** [Chainmail-Studios/Astromine#128]
minecraft 1.16.1
astromine 1.0.18
ok zoomer 4.0.0 alpha.3
fabric api 1.14.1 (unrelated)
fabric loader 0.8.8 build 202

disabling astromine allows okzoomer to work again
enabling astromine causes the zoom to not function

looks to be an incompatibility in the FOV mixin

**Comment by vini2003** [comment]
Fixed reasonably well in newer versions; you can zoom in normally, except when holding a weapon.
