### ISSUE TITLE
1.0.20 crashes with patchouli

### ISSUE THREAD

**Issue by Linguardium** [Chainmail-Studios/Astromine#129]
crash with patchouli https://paste.ee/p/Zgk99
no crash without https://paste.ee/p/4AcwL

**Comment by Linguardium** [comment]
Another note, 1.0.18 did not crash

**Comment by Shnupbups** [comment]
The mod bundles a newer version of Patchouli which is required.

**Comment by Linguardium** [comment]
so is it safe to assume we are waiting for curse to approve the new release version and that there is no currently compatible release version (unless you build it from source)?

**Comment by Shnupbups** [comment]
There is no compatible version on Curse, but that isn't an issue as the mod *includes the compatible version*. As in, if the mod is installed, Patchouli is too.

**Comment by Linguardium** [comment]
yes, but there is literally no indication that the mod includes the only compatible, built from source, version of a mod that is likely to be used for other mods in a list. your mod literally breaks if someone is already using the latest release of a mod your require.
