### ISSUE TITLE
Add 1.7.10 Forge Mod.

### ISSUE THREAD

**Issue by devomaa** [Chainmail-Studios/Astromine#137]

**Comment by vini2003** [comment]
no

**Comment by AK9Official** [comment]
no

**Comment by Draylar** [comment]
yes

**Comment by CoolMineman** [comment]
I recommend this stays closed. 1.7.10 Forge is much better and has more epic mods.

**Comment by Devan-Kerman** [comment]
you're right, let's port it to 1.7.10 forge

**Comment by Devan-Kerman** [comment]
we live in a mod dev powered society, and the mod devs said no

**Comment by devomaa** [comment]
i ment 1.12.2 :P

**Comment by Shnupbups** [comment]
and we meant no :P

**Comment by shedaniel** [comment]
I meant 1.2.5 :p

**Comment by CoolMineman** [comment]
I spelled b1.7.3 fabric wrong :tinypotato:

**Comment by shedaniel** [comment]
Our response is no, we don't want to port to Forge, if someone wants to do that for us, go ahead, we can't stop you because of our license.

A port will come if it comes.

**Comment by AK9Official** [comment]
craftbukkit port when

**Comment by CoolMineman** [comment]
fukkit support when?

**Comment by SuperCoder7979** [comment]
pee pee poo poo

**Comment by Devan-Kerman** [comment]
Fukkit support soon tm
