### ISSUE TITLE
Instantaneous crash when starting game.

### ISSUE THREAD

**Issue by Kirti773** [Chainmail-Studios/Astromine#138]
No matter what other mods I use (even with no other mods at all) the game just crashes when starting up.

crash log and error message are listed below.

I don't know if anyone else has this problem.

![error](https://user-images.githubusercontent.com/59840931/86421400-35385c80-bcda-11ea-980a-0a94fa1dcd51.PNG)
[crash-2020-07-03_02.59.45-client.txt](https://github.com/Chainmail-Studios/Astromine/files/4867228/crash-2020-07-03_02.59.45-client.txt)

**Comment by shedaniel** [comment]
Update Fabric API
