### ISSUE TITLE
Patchouli not working very well in modpack: All of Fabric 3

### ISSUE THREAD

**Issue by HaloSense** [Chainmail-Studios/Astromine#141]
As I wrote in the title, I am playing a modpack with Astromine, Patchouli and REI (Roughly Enough Items) inside. REI tells me to craft a guidebook for astromine with a book and a seed, which doesn't look right. And I crafted a wrong book. How am I supposed to fix this? Which issue/pull request should I look into?

**Comment by vini2003** [comment]
We have added a procedure to acquire the Astromine manual: right-click a Bookshelf with a Metite Axe.
