### ISSUE TITLE
Crash when any entity touches Honey blocks

### ISSUE THREAD

**Issue by TelepathicGrunt** [Chainmail-Studios/Astromine#144]
This mixin will crash the game as `this` is a Honey Block and is trying to be casted into an Entity
https://github.com/Chainmail-Studios/Astromine/blob/4999e284ab514c49a9d096a6f6705c1056275904/src/main/java/com/github/chainmailstudios/astromine/mixin/HoneyBlockMixin.java#L17

I suspect this crash would also happen with this mixin as well as StepAndDestroyBlockGoal isnt an entity I believe.
https://github.com/Chainmail-Studios/Astromine/blob/4999e284ab514c49a9d096a6f6705c1056275904/src/main/java/com/github/chainmailstudios/astromine/mixin/StepAndDestroyBlockGoalMixin.java#L17

I only know about the issue because someone reported the honey block crash to me with this unmapped crashlog: https://hatebin.com/vftmieutpm Since The bumblezone has so much honey blocks, Astromine's mixin will crash the dimension very quickly without letting players enter it.

Though this is just a very simple fix so hopefully a patch will be out soon. :)

**Comment by shedaniel** [comment]
We have disabled that mixin in 1.0.30
