### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Miros77** [Chainmail-Studios/Astromine#148]
![mod](https://user-images.githubusercontent.com/59547044/87213127-482adc80-c32b-11ea-9683-4c3b142b7b1a.JPG)
fabric-loader-0.8.9+build.203-1.16.1

mod
astromine-1.0.29+fabric-1.16.1
preview_OptiFine_1.16.1_HD_U_G2_pre2
optifabric_1.16.1_1.1.0_beta2
fabric_api_0.14.1build.372_1.16

[crash-2020-07-11_03.41.38-client.txt](https://github.com/Chainmail-Studios/Astromine/files/4906081/crash-2020-07-11_03.41.38-client.txt)

**Comment by shedaniel** [comment]
we don't support optifine AND pirated minecraft

**Comment by Miros77** [comment]
why does my mod run without optifine

**Comment by shedaniel** [comment]
buy minecraft, shut up.
