### ISSUE TITLE
Energy cable not working when you reload a world until you replace apart of it (kinda)

### ISSUE THREAD

**Issue by justinvvitale** [Chainmail-Studios/Astromine#156]
Hello, I was doing some *cough* testing with your energy network cables unrelated to what I am doing with Tech Reborn 😏 and I think I found an issue when you unload a world and load it again. From what I've seen, when you have an energy provider on the network and you unload it, then load it again (Not chunks, they seem fine (I think, I don't believe they unload tho?), you need to break and place a cable for it to work again.

Video demonstrating the problem (if it is one)
https://www.youtube.com/watch?v=my2tV-ZZNsQ

**Comment by vini2003** [comment]
Fixed.
