### ISSUE TITLE
NoSuchMethodError when rendering screen

### ISSUE THREAD

**Issue by Boundarybreaker** [Chainmail-Studios/Astromine#157]
`drawTexturedQuad` can't be found when attempting to render the Astromine fluid extractor screen, resulting in a crash, according to [All-Of-Fabric-3#19](https://github.com/TeamAOF/All-of-Fabric-3/issues/19)
[log](https://github.com/Chainmail-Studios/Astromine/files/4941476/minecraft-exported-logs-2020-07-18T18-27-09.log)

**Comment by vini2003** [comment]
Not reproducible.
