### ISSUE TITLE
No bronze

### ISSUE THREAD

**Issue by Yougotcheezed** [Chainmail-Studios/Astromine#163]
No current recipe for bronze. Cant build circuits

**Comment by vini2003** [comment]
Fixed.

**Comment by irunatbullets** [comment]
This still seems to be a problem in astromine-1.5.2+fabric-1.16.1.jar. If this was fixed for 1.16.2 would it be possible to back port it for 1.16.1?

I'm playing using AOF3 which has Tech Reborn. Bronze plates from Tech Reborn can be used for some of the recipes in Astromine but not for things like conveyor belts. When I build an Astromine Presser to get Astromine bronze plates it just produces Tech Reborn plates instead.
