### ISSUE TITLE
Version 1.3.3 Crashes game upon entering Space

### ISSUE THREAD

**Issue by el0c** [Chainmail-Studios/Astromine#176]
Log: https://paste.ee/p/eXVFO

Tested the mod by itself on the most recent version of Fabric Loader (0.9.0+build.204) and Fabric API (0.15.1+build.380) for 1.16.1.

Steps to reproduce quickly: 
- Enter a new world with cheats
- /tp ~ 1024 ~ 
- You should change dimensions, see the Minecraft earth then crash quickly afterwards.

**Comment by ZarikTH** [comment]
i got the exact same crash.

**Comment by vini2003** [comment]
Found and fixed.
