### ISSUE TITLE
[1.16.1] InvocationTargetException at launch

### ISSUE THREAD

**Issue by Fogrits** [Chainmail-Studios/Astromine#179]
![image](https://user-images.githubusercontent.com/14002834/88366918-d4dc8e00-cd60-11ea-9320-2993b94db8cc.png)
Latest version (1.3.4)

**Comment by Shnupbups** [comment]
Will fix!

**Comment by Fogrits** [comment]
It seems like a compatibility issue with mods that alters the Attack Speed attribute

**Comment by Fogrits** [comment]
In that case, CombatEdit (mod that I'm using, which removes the attack speed attribute entirely)

**Comment by Shnupbups** [comment]
Ah yes, that would *definitely* cause an issue, thanks. Knowing that makes it easier to fix!

**Comment by Shnupbups** [comment]
Fixed in dev.
