### ISSUE TITLE
Assorted GUI issues

### ISSUE THREAD

**Issue by emilyploszaj** [Chainmail-Studios/Astromine#185]
Didn't want to spam issues so here's a list of things I've noticed with astromine GUIs
* Background is notably darker than vanilla, can be easily noticed if you check a recipe while in a machine, the background will get lighter (maybe drawing the transparent layer twice?)
* Splitting an odd stack has the opposite behavior compared to vanilla, if you right click on 3 items you will pick up 1 and leave 2
* The energy bar can be a little bit jittery when energy is changing
* Some aspects seem to be slightly offset, like quantity being drawn a handful of pixels off

**Comment by shedaniel** [comment]
The first issue has been fixed in dev. @vini2003 please do follow up on the other issues

**Comment by vini2003** [comment]
Morning', I've made and switched to a new GUI library and all those issues are solved in development.

**Comment by Shnupbups** [comment]
Yes, the issues have been replaced with new ones :)

**Comment by vini2003** [comment]
![:shut:](https://cdn.discordapp.com/emojis/646363901440819200.png?v=1)

**Comment by MariaTheDinkus** [comment]
These bugs are fixed in the latest 1.16.2 Astromine.
