### ISSUE TITLE
Meteor can spawn in ocean biome

### ISSUE THREAD

**Issue by SFort** [Chainmail-Studios/Astromine#186]
![meteor](https://user-images.githubusercontent.com/1879846/88603101-abbf4480-d063-11ea-9a66-02744b4408c2.png)

**Comment by SuperCoder7979** [comment]
i'm pretty sure this is a feature for now, will look into fixing it soon

**Comment by Danklor** [comment]
Look! It floats! (chuckle)

At least it's an interesting... feature.

![2020-08-07_03 04 13](https://user-images.githubusercontent.com/9893553/89619039-39b4df80-d85b-11ea-87e8-1808984d5f5d.png)

**Comment by TelepathicGrunt** [comment]
I got a similar thing too lol. So much floating water
![image](https://user-images.githubusercontent.com/40846040/89896193-094aa980-dbab-11ea-8218-46c74491470b.png)

**Comment by tim-blackbird** [comment]
Could be cool to find meteors at the bottom of the ocean (instead of on top q: ). The fire could then be magma blocks!

**Comment by shedaniel** [comment]
With the 1.16.2 updates, they already spawn under water:
![](https://cdn.discordapp.com/attachments/720420923177435136/744089207772807188/unknown.png)
