### ISSUE TITLE
Crash at startup when paired with optifabric

### ISSUE THREAD

**Issue by technomancer21** [Chainmail-Studios/Astromine#194]
I realise this has to do with other mods, however if I'm reading this log right, astromine is failing to interact with the rendering engine?
I don't know much about reading log files, so I'll just post the file itself, hopefully that will help.

I have confirmed it is related to using optifine / optifabric, as it worked fine prior to installing them, and after removing them.
Mod jars as follows:
Optifabric-1.1.0-beta2.jar
Optifine_1.16.1_HD_U_G2.jar
astromine-1.4.3+fabric-1.16.1.jar

[2020-08-04-6.log](https://github.com/Chainmail-Studios/Astromine/files/5017423/2020-08-04-6.log)

**Comment by shedaniel** [comment]
we don't support optifine

**Comment by Miros77** [comment]
Use Sodium

**Comment by technomancer21** [comment]
I have been, the only reason I wanted optifine was for shader support, I cannot seem to find any other way to implement shaders outside of optifine, but if its a lost cause then I'll happily accept that you don't support optifine, I just figured I'd take the chance and report the crash anyway.

**Comment by shedaniel** [comment]
it's too much effort supporting an abandoned mod loading a proprietary mod.

**Comment by technomancer21** [comment]
Thats fair enough. I'll just hold out hope that canvas someday supports traditional shader packs as well as its own implementation. Thank you for the response though. Much obliged.

**Comment by Chocohead** [comment]
For reference this should be fixed with OptiFabric v1.4.8 for anyone still using 1.16.1
