### ISSUE TITLE
Translated the mod into Russian

### ISSUE THREAD

**Issue by Miros77** [Chainmail-Studios/Astromine#196]
[ru_ru.zip](https://github.com/Chainmail-Studios/Astromine/files/5031708/ru_ru.zip)

add Russian to the lang folder

**Comment by Miros77** [comment]
To connect the Russian Language to mod

**Comment by vini2003** [comment]
Will check out tomorrow!

**Comment by Miros77** [comment]
Ok

**Comment by vini2003** [comment]
Yeah sorry I forgot to, but I will get around to it. I swear.

**Comment by vini2003** [comment]
Alright seems good, I've merged with my branch, will be released when I merge onto master.

**Comment by MariaTheDinkus** [comment]
This is in the latest build of Astromine for 1.16.2.

**Comment by Miros77** [comment]
> This is in the latest build of Astromine for 1.16.2.

thanks
