### ISSUE TITLE
Fluid mixer and other fluid problems

### ISSUE THREAD

**Issue by astocky** [Chainmail-Studios/Astromine#197]
Using version 1.5.0.
When I extract using fluid pipes from an electrolyzer  into a fluid mixer, extracting 1 unit (1 bucket of oxygen) fills all three slots of the fluid mixer (both inputs and output) with 4 buckets of oxygen. I tried starting with a bucket of lava in the first mixer slot and it just fills all the slots with oxygen anyway.
The electrolyzer seems to make oxygen and hydrogen normally, but the insertion into the mixer seems broken. 
Tanks also do not connect with the fluid pipes so I couldn't work out a way to use them to make the input process work.
Please let me know if you need any additional details, I don't see any errors in the log.

**Comment by vini2003** [comment]
Solved.
