### ISSUE TITLE
Crash when entering the Nether

### ISSUE THREAD

**Issue by KitaenSilva** [Chainmail-Studios/Astromine#199]
Copy and paste from my original Curseforge comment:

> I didn't expect Astromine to touch "Piglin Brain" or much else to do with mobs, but I seem to have encountered a strange crash with minimal description when entering the Nether, and a scan of the crash log for any clues to the cause and a possible fix have only pointed toward Astromine.
> 
> I have a very large Fabric mod pack which I update on Wednesdays and am documenting in a Google Doc, so there could very likely be some sort of unexpected interaction going on here, but Not Enough Crashes is fortunately among the list to help with troubleshooting and such.
> 
> For now, things seem more or less fine as long as I don't venture off into the Nether, and I have a lot to do in my world that doesn't involve the Nether right yet, so I can wait for any potential update, but figure I should make a quick mention of it.
> 
> Line 75 of this paste is pretty much my primary indicator of where I could begin to look for a possible solution.
> 
> https://pastebin.com/uprBa7g8
> 
> It very well could be another case of pebcak on my part, goodness knows i've had several cases of that already trying to build this nonsense kitchen sink exploration pack.
> 
> Thank you for what has so far been an enjoyable mod, and thank you for developing for Fabric~!
> 
> Edit 1: Minimal layman-comprehensible description, apologies.
> 
> Edit 2: I need to get better about looking for the Issues tab on mods, as this is the second time I failed to notice it until after I posted. I can move this bug report to the issue tracker if preferred.

Additional comments...

It was replied that the crash issue is related to a conflicting mod, so I apologize for the exorbitantly lengthy mod list in the pastebin - I personally don't comprehend much of the crash log, or at least not enough to narrow down the conflict, but if it'll help in some way or at least save some time, I am happy to put some effort into dissecting my pack in order to narrow down the conflicting mod(s).

**Comment by Shnupbups** [comment]
The conflict is with 'Piglin Tag', which uses a more invasive mixin than we do to achieve the same affect, but in doing so causes the mods to really not like each other.

I don't know if you have Piglin Tag itself installed or a mod that bundles it. If you have it installed as its own thing, you can remove it as Astromine implements its functionality. If it's another mod bundling it, I can try to figure out which mod it is.

**Comment by shedaniel** [comment]
Piglin Tag is extremely invasive, https://github.com/Globox1997/PiglinTag/blob/master/src/main/java/net/piglintag/mixin/PiglinBrainMixin.java

It will be quite annoying to get this fixed.

**Comment by KitaenSilva** [comment]
I don't actually have Piglin Tag, but I do have AdventureZ by the same mod author, and it features a block/item that seems to do what Piglin Tag describes, so let me cut my pack down to the latest Astromine, the Fabric API, and AdventureZ to see what happens... once I get some breakfast in me.

I've actually been having quite a lot of trouble with Globox_Z's mods all-around, as adding most of them causes crashes or other issues, so I might remove it from my pack even if it isn't the culprit just to save myself a headache later. Guess I'll have to hold out for boss and mob mods, heh.

**Edit**: Wew lad, that guess was spot-on. Seems AdventureZ bundles Piglin Tag into itself - probably for their Piglin Flag block/item which does pretty much what the Piglin Tag mod describes. I _also_ confirmed that [comment number 196](https://www.curseforge.com/minecraft/mc-mods/astromine-fabric?comment=196) is related, which in thinking about it, makes sense if opening chests now checks for nearby piglins or however that works.

**Edit 2**: Reduced my pack down to [AdventureZ 1.0.7](https://www.curseforge.com/minecraft/mc-mods/adventurez), Fabric API 0.16.2 Build 385, and Astromine 1.5.2 to test. Using this setup, here's a fresh crash log from when [opening a chest](https://pastebin.com/aUMVBzY9), and here's a fresh one from [entering the Nether](https://pastebin.com/JpNcfQ7X).

**Comment by Shnupbups** [comment]
Gonna close as this isn't our issue
