### ISSUE TITLE
(1.16.2, Astromine 1.7.0) Crash when viewing Astromine's armor

### ISSUE THREAD

**Issue by InvitedRhino683** [Chainmail-Studios/Astromine#213]
Whenever I try to look at my inventory or look in third person with Astromine's armor on, I immediately crash. I've been able to recreate this crash by simply wearing some armor and then going into my inventory.
[crash-2020-08-18_19.00.33-client.txt](https://github.com/Chainmail-Studios/Astromine/files/5093380/crash-2020-08-18_19.00.33-client.txt)

**Comment by vini2003** [comment]
@shedaniel oopsie.

**Comment by Shnupbups** [comment]
fixed in dev
