### ISSUE TITLE
1.16.2/Astromine 1.7.0 - Server crash: ArithmeticException: / by zero

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#217]
[crash-2020-08-21_20.19.52-server.txt](https://github.com/Chainmail-Studios/Astromine/files/5111091/crash-2020-08-21_20.19.52-server.txt)

I used REI to spawn in a charged block breaker.  The moment I put it down, this crash happened.
After letting the server restart without astromine, joining, then restarting again to put astromine back in, all was good again.

**Comment by vini2003** [comment]
There's a chance this was already fixed, but anyhow, our first fraction crash! Nice!
