### ISSUE TITLE
Index Out of Bounds Exception when viewing machinery gui

### ISSUE THREAD

**Issue by technomancer21** [Chainmail-Studios/Astromine#218]
I was watching my primitive alloy smelter finish processing some bronze ingots when my game crashed. I cant really make heads or tails of the crash log so I thought I might drop it in here. 
It is a custom modpack, I don't know if there are any unsupported mods in there, I don't believe so but there is a list in the crash log so feel free to slap me if I've oopsed and used something I shouldn't have.

[crash-2020-08-23_00.54.22-client.txt](https://github.com/Chainmail-Studios/Astromine/files/5112549/crash-2020-08-23_00.54.22-client.txt)

**Comment by shedaniel** [comment]
InventorySorter's issue
