### ISSUE TITLE
1.16.2/1.7.0 Holographic bridge doesn't display

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#220]
After linking opposite holographic bridge projectors, a bridge is created and can be walked on.  However the holographic blocks themselves don't display.

There were no errors on the client or server console when linking was done.

![image](https://user-images.githubusercontent.com/918422/90988688-02ea0380-e595-11ea-8baa-fb36bb0ebad2.png)

**Comment by vini2003** [comment]
Solved; `alpha` of the texture was zero - oops.
