### ISSUE TITLE
Concarrn

### ISSUE THREAD

**Issue by Neubulae** [Chainmail-Studios/Astromine#222]
![image](https://user-images.githubusercontent.com/24774842/91051682-0774f180-e653-11ea-9323-3368918558d8.png)
![image](https://user-images.githubusercontent.com/24774842/91051715-13f94a00-e653-11ea-8b7a-9801954f560a.png)
:concern:

**Comment by shedaniel** [comment]
It is fixed in dev with altar infusing

**Comment by Neubulae** [comment]
> It is fixed in dev with altar infusing

perfect now I can craft tons of it and make myself rich :yate
