### ISSUE TITLE
ClassCastException in BossBarHudMixin

### ISSUE THREAD

**Issue by ianmeinert** [Chainmail-Studios/Astromine#223]
When using the https://uncensoredlibrary.com/en map and astromine mod together, I receive the below error

[23:13:58] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.class_2585 cannot be cast to net.minecraft.class_2588
	at net.minecraft.class_337.handler$zkg000$renderCustomBossBar(class_337.java:559)

After the error is thrown, the instance crashes.

**Comment by ianmeinert** [comment]
I should also mention we are using v1.5.2 and fabric 1.16.1

**Comment by shedaniel** [comment]
that version is not supported anymore

**Comment by ianmeinert** [comment]
But it was current when submitted. Has the issue been resolved in the latest version?

**Comment by ianmeinert** [comment]
@shedaniel Issue still persists using fresh deployment of MC 1.16.2, Fabric 0.9.2+build.206 and Astromine 1.8.5

> ---- Minecraft Crash Report ----
> // Hey, that tickles! Hehehe!
> 
> Time: 9/3/20 9:46 PM
> Description: Unexpected error
> 
> java.lang.ClassCastException: net.minecraft.class_2585 cannot be cast to net.minecraft.class_2588
> 	at net.minecraft.class_337.handler$zol000$renderCustomBossBar(class_337.java:562)
> 	at net.minecraft.class_337.method_1799(class_337.java)
> 	at net.minecraft.class_337.method_1796(class_337.java:44)
> 	at net.minecraft.class_329.method_1753(class_329.java:206)
> 	at net.minecraft.class_757.method_3192(class_757.java:597)
> 	at net.minecraft.class_310.method_1523(class_310.java:1023)
> 	at net.minecraft.class_310.method_1514(class_310.java:656)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.class_337.handler$zol000$renderCustomBossBar(class_337.java:562)
> 	at net.minecraft.class_337.method_1799(class_337.java)
> 	at net.minecraft.class_337.method_1796(class_337.java:44)
> 	at net.minecraft.class_329.method_1753(class_329.java:206)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['PogLife4Me'/1, l='ClientLevel', x=1463.50, y=68.00, z=1413.14]]
> 	Chunk stats: Client Chunk Cache: 841, 529
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (1463,12,1974), Chunk: (at 7,0,6 in 91,123; contains blocks 1456,0,1968 to 1471,255,1983), Region: (2,3; contains chunks 64,96 to 95,127, blocks 1024,0,1536 to 1535,255,2047)
> 	Level time: 249350462 game time, 96000 day time
> 	Server brand: fabric
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:449)
> 	at net.minecraft.class_310.method_1587(class_310.java:2183)
> 	at net.minecraft.class_310.method_1514(class_310.java:679)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.2
> 	Minecraft Version ID: 1.16.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_261, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 3045029296 bytes (2903 MB) / 4322230272 bytes (4122 MB) up to 9544663040 bytes (9102 MB)
> 	CPUs: 12
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10240m
> 	Fabric Mods: 
> 		angerable-patch: Angerable Patch 1.0.0-1.16.1
> 		appleskin: AppleSkin 1.0.11
> 		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.5
> 		astromine: Astromine 1.8.5+fabric-1.16.2
> 		astromine-core: Astromine: Core 1.8.5+fabric-1.16.2
> 		astromine-foundations: Astromine: Foundations 1.8.5+fabric-1.16.2
> 		astromine-technologies: Astromine: Technologies 1.8.5+fabric-1.16.2
> 		astromine-transportations: Astromine: Transportations 1.8.5+fabric-1.16.2
> 		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
> 		backpackmod: Backpack Mod 1.16.2-1.2.1
> 		blade: Blade 1.0.1
> 		blue_endless_jankson: jankson +
> 		byg: BYG 1.0.5
> 		campanion: Campanion 1.2.0+build.39
> 		cardinal-components-base: Cardinal Components API (base) 2.5.2
> 		cardinal-components-block: Cardinal Components API (blocks) 2.5.2
> 		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.2
> 		cardinal-components-entity: Cardinal Components API (entities) 2.5.2
> 		cardinal-components-item: Cardinal Components API (items) 2.5.2
> 		cardinal-components-level: Cardinal Components API (world saves) 2.5.2
> 		cardinal-components-util: Cardinal Components API (utilities) 2.5.2
> 		cardinal-components-world: Cardinal Components API (worlds) 2.5.2
> 		cavebiomes: Cave Biomes 0.3.0
> 		chainmail: Chainmail 0.5.0
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-client-events-v0: Cloth Client Events v0 1.4.5
> 		cloth-config2: Cloth Config v4 4.8.1
> 		cloth-datagen-api-v1: Cloth Datagen v1 1.4.5
> 		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.5
> 		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.5
> 		diggusmaximus: Diggus Maximus 1.3.1-1.16
> 		dishes: Delicious Dishes 1.0.4
> 		enderitemod: Enderite Mod 1.2.2
> 		expandedstorage: ExpandedStorage 5.5.23
> 		fabric: Fabric API 0.19.0+build.398-1.16
> 		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
> 		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
> 		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
> 		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
> 		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
> 		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
> 		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
> 		fabricloader: Fabric Loader 0.9.2+build.206
> 		fermion: Fermion 2.1.191
> 		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
> 		fiber: fiber 0.23.0-1
> 		improved-stations: Improved Stations 2.0.3
> 		indrev: Industrial Revolution 1.6.1
> 		jankson: Jankson 3.0.1+j1.2.0
> 		kibe: Kibe 1.3.3-BETA
> 		kyrptconfig: Kytpt Config 1.1.2-1.16
> 		libblockattributes_core: LibBlockAttributes (Core) 0.8.1
> 		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
> 		libblockattributes_items: LibBlockAttributes (Items) 0.8.1
> 		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
> 		libstructure: LibStructure 1.5
> 		lithium: Lithium 0.5.4
> 		magna: Magna 1.4.0-1.16.2
> 		minecraft: Minecraft 1.16.2
> 		modmenu: Mod Menu 1.14.6+build.31
> 		org_jetbrains_annotations: annotations 17.0.0
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
> 		patchouli: Patchouli 1.16-40-FABRIC
> 		playerabilitylib: Pal 1.2.0
> 		pugh_lib: Pugh Lib 1.0.2
> 		reach-entity-attributes: Reach Entity Attribute 1.0.1
> 		reborncore: Reborn Core 4.4.0+build.67
> 		repurposed_structures: Repurposed Structures 1.16.2-1.5.2
> 		roughlyenoughitems: Roughly Enough Items 5.2.10
> 		roughlyenoughitems-api: REI (API) 5.2.10
> 		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.10
> 		roughlyenoughitems-runtime: REI (Runtime) 5.2.10
> 		sandwichable: Sandwichable 1.1.2
> 		shapes: Shapes 2.0.0+build.10
> 		team_reborn_energy: Energy 0.1.0
> 		techreborn: Tech Reborn 3.5.1+build.101
> 		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
> 		veggie_way: The Veggie Way 1.0.29
> 		voxelmap: VoxelMap 1.10.10
> 		waila: Hwyla 1.9.22
> 		wrenchable: Wrenchable 1.0.0+1.16.1
> 	Patchouli open book context: n/a
> 	Launched Version: MultiMC5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 26.20.100.8141, Intel
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: 
> 	Current Language: English (US)
> 	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by shedaniel** [comment]
It's fixed in dev, will be shipped together with the next update.
