### ISSUE TITLE
Add animation to Univite Armor texture; and rework it entirely

### ISSUE THREAD

**Issue by Desempregago** [Chainmail-Studios/Astromine#229]
![2020-08-25_21 39 48](https://user-images.githubusercontent.com/14002834/91241619-b67d0000-e71b-11ea-95c8-64bd817ae35d.png)

And what if Univite armor had animated textures, just like the tools?

**Comment by vini2003** [comment]
Animating armor textures is a lot more involved than animated item textures; would require more hacks. Won't do for now.

**Comment by shedaniel** [comment]
no it's not, the hard part is making the png

**Comment by vini2003** [comment]
can we use mcmeta for it?
i was told we couldnt

**Comment by shedaniel** [comment]
just send me the png ill make it work yes

**Comment by vini2003** [comment]
We have animated it. Art will come at a later date.
