### ISSUE TITLE
"Worlds using Experimental Settings are not supported"

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#238]
Every time I create a world with Astromine installed, I get a warning about experimental settings. I know that this message doesn't appear when Astromine isn't installed. It would be nice to know what causes this and if I can safely ignore it.

- Minecraft 1.16.2
- Fabric Loader 0.9.2+build.206
- fabric-api-0.19.0+build.398-1.16
- astromine-1.8.5+fabric-1.16.2

![screenshot](https://user-images.githubusercontent.com/3250809/91637391-5b435a00-ea08-11ea-925f-90b10082ed67.png)

**Comment by Shnupbups** [comment]
You can ignore it. This only shows up because we add dimensions and biomes using JSONs, a feature Mojang has decided to put behind this annoying screen.
