### ISSUE TITLE
Tank Issues

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#239]
1. When right-clicking the tank with an empty bucket the amount of liquid in the tank decreased by one bucket, but the bucket in hand stays empty (liquid is essentially voided)

2. When outputting liquid to another machine (in my case Advanced Liquid Generator) the machine gets the liquid, but the amount of liquid in tank doesn't decrease (liquid is essentially infinite)

**Comment by vini2003** [comment]
Solved.
