### ISSUE TITLE
It spams packets

### ISSUE THREAD

**Issue by falseresync** [Chainmail-Studios/Astromine#240]
I don't know why, but when I've added a debug logger for my packet, I saw that Astromine spams `astromine:pressure_update` packets. It sends that packet each tick to each player
![Screenshot (5)](https://user-images.githubusercontent.com/17195973/91655736-99e61c80-eabb-11ea-9fd7-28c105375d33.png)
Version: 1.5.2 for 1.16.1 on AOF 3

**Comment by shedaniel** [comment]
Please test the latest astromine release on this issue

**Comment by falseresync** [comment]
I have troubles logging into the server with Astromine 1.8.5, Fabric complains about registry desync

![Screenshot (6)](https://user-images.githubusercontent.com/17195973/91656636-06b0e500-eac3-11ea-92c6-1770324a7548.png)

Does it need a dependency? I have only it, FAPI and my mod installed now

P.S. And after a few login failures, server also freezes
P.P.S. I tried removing `.fabric` on both client and server

**Comment by shedaniel** [comment]
Do you have a log with errors on the server or the client?

**Comment by falseresync** [comment]
There’re no errors in the log, only this message

**Comment by vini2003** [comment]
Solved; though we do still send packets for atmospheric gasses, there is no way around that.
