### ISSUE TITLE
Astromine 1.9.0 falling from earth causes disconnect and no reconnect

### ISSUE THREAD

**Issue by Monster-Zer0** [Chainmail-Studios/Astromine#244]
Fabric API 0.19.0+build398-1.16
MC 1.16.2
Dedicated server

when falling from earth, the moment  you transition back to earth you are disconnected from server and then unable to log back in. I had to delete player data in order to log back in.

here is the log from the moment that the disconnect happens

https://hastebin.com/uwufitihaj.makefile

**Comment by vini2003** [comment]
end me

**Comment by MariaTheDinkus** [comment]
ok

**Comment by Shnupbups** [comment]
Your hastebin link seems to be empty, if you could provide us with the log that would be great!

**Comment by vini2003** [comment]
Preferably avoid hastebin; it's been doing all sorts of cursed things lately, _especially_ magically emptying itself.

**Comment by ImAK9** [comment]
Vini i love you

**Comment by MariaTheDinkus** [comment]
i love forge

**Comment by Monster-Zer0** [comment]
Hastebin go boom

Here is paste elsewhere



https://paste.gg/p/anonymous/9139d4754a20436fbc7d7b2d55a2e2e5
