### ISSUE TITLE
Crash at startup when paired with optifabric 1.16.2 (optifabric-1.4.5.jar)

### ISSUE THREAD

**Issue by Jarfeh** [Chainmail-Studios/Astromine#249]
I know there was an earlier issue closed because you don't support outdated mods, but someone has picked optifabric back up and is now actively working on it again.
https://paste.ee/p/UjKN0

**Comment by shedaniel** [comment]
Fixed in OptiFabric 1.4.7

**Comment by Jarfeh** [comment]
thank you
