### ISSUE TITLE
Crash upon entering space.

### ISSUE THREAD

**Issue by Topshelf2020** [Chainmail-Studios/Astromine#252]
Instantly crashing upon loading into space, happens every time I load back into the server. This is on All of Fabric 2.0.1.

https://pastebin.com/Niw3qsgQ

**Comment by vini2003** [comment]
The elusive LivingEntityMixin crash that only a few are able to reproduce. Excellent.

**Comment by shedaniel** [comment]
smh just put it in a try catch

**Comment by vini2003** [comment]
massive brain

**Comment by vini2003** [comment]
Solved.
