### ISSUE TITLE
Crash when placing buffer

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#253]
In All of Fabric 3 (1.5.3), 
placing a buffer next to an autocrafting table from Tech Reborn auto pulling into the buffer crash instantly the game.
Restarting the save will crash at the opening of the world.

[crash-2020-09-06_01.11.13-server.txt](https://github.com/Mixinors/Astromine/files/5178859/crash-2020-09-06_01.11.13-server.txt)

**Comment by vini2003** [comment]
Unable to reproduce; attempts result in error from TechReborn's side, sometimes it works, sometimes it doesn't, but it does not appear to be our fault.

**Comment by vini2003** [comment]
I will, however, report this to their repository.

**Comment by vini2003** [comment]
https://github.com/TechReborn/TechReborn/issues/2220
