### ISSUE TITLE
Recipe conflict with Tech Reborn

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#254]
Astromine and Tech Reborn both add a recipe with the following shape:

```
-------------
|   | x |   |
-------------
| x |   | x |
-------------
|   | x |   |
-------------
```

where x = tin. The Tech Reborn recipe makes Empty Cells, the Astromine recipe adds Tin Gear.

**Comment by vini2003** [comment]
Won't fix; universal gear recipe will remain - either we change everything or accept this problem.

Use a recipe cycling mod or change with KubeJS.
