### ISSUE TITLE
Fluids do not have names

### ISSUE THREAD

**Issue by williambl** [Chainmail-Studios/Astromine#261]
The fluids added by astromine do not have names. (more accurately, the blocks of the fluids do not have names). This causes issues for mods that try to show the names of fluids in containers.
![Screenshot_20200908_195238](https://user-images.githubusercontent.com/5115825/92516372-a88faa80-f204-11ea-81d9-15d9eb8f4f66.png)

**Comment by vini2003** [comment]
Solved.
