### ISSUE TITLE
cant craft primitive machine chassis

### ISSUE THREAD

**Issue by bogggle** [Chainmail-Studios/Astromine#267]
with Roughly Enough Items (fabric) i can see that to craft a primitive machine chassis u need 4 tin plates and 4 copper plates in a crafting bench. i put them in in the correct way and nothing appears? was wondering if anyone can help?
![machine chassis recipe](https://user-images.githubusercontent.com/71095810/92780374-f76f4880-f39a-11ea-93ab-3f7bd581b876.JPG)
![machine chassis not crafting](https://user-images.githubusercontent.com/71095810/92780384-f9390c00-f39a-11ea-839c-0266675ccea8.JPG)

**Comment by shedaniel** [comment]
update REI, I released a broken version of REI
