### ISSUE TITLE
Astromine incompatible with Immersive Portals

### ISSUE THREAD

**Issue by watersofnazareth** [Chainmail-Studios/Astromine#268]
Game crashes immediately upon trying to open a world or hitting create new world, crash log:
https://pastebin.pl/view/717778bd

**Comment by vini2003** [comment]
Not sure what's wrong, but also not terribly interested in compatibility with IP - wouldn't be our first issue.
Maybe someone else can take a look.

**Comment by vini2003** [comment]
This does not appear to be our fault.

**Comment by vini2003** [comment]
Poke the Overworld Two developers.
