### ISSUE TITLE
Strongholds generate in Earth Space

### ISSUE THREAD

**Issue by TrueCP6** [Chainmail-Studios/Astromine#270]
![image](https://user-images.githubusercontent.com/39642832/92994251-184db000-f4f9-11ea-8d97-15d0037cfe45.png)

**Comment by shedaniel** [comment]
I crave death

**Comment by vini2003** [comment]
omegaconcern

**Comment by vini2003** [comment]
Reproducible; happens because we do not use the vanilla noise generator.

Thanks, Mojang.

**Comment by vini2003** [comment]
Wait; this should have been fixed.

**Comment by vini2003** [comment]
Yep, thanks to whoever fixed it!
