### ISSUE TITLE
Stacked buckets get deleted by fluid blocks

### ISSUE THREAD

**Issue by Floofball-uwu** [Chainmail-Studios/Astromine#273]
Stacked buckets get deleted (but one) when getting fluid from a Liquid Generators or tanks.

Steps to reproduce:
1. Get two or more buckets stacked.
2. Right-click a Liquid Generator or a tank with the buckets.

Result:
Only one bucket with the chosen fluid will remain. The other buckets in the stack get deleted.

**Comment by vini2003** [comment]
Solved.
