### ISSUE TITLE
Creative Tank fluid type cannot be changed

### ISSUE THREAD

**Issue by SauceOfficial** [Chainmail-Studios/Astromine#288]

**Comment by lineargraph** [comment]
The creative tank is probably fixed in #286

**Comment by vini2003** [comment]
Unsure what you meant by filling the rocket up with fluid storage blocks, however, it is meant to be filled by hand with Canisters or Buckets in its GUI.

Creative Tank issue has been solved.

**Comment by SauceOfficial** [comment]
I meant that ex. You can’t use built in (mod) tanks, so you cant use an creative tank to fill up a rocket, not an storage ITEM. Wysłane z aplikacji Poczta dla Windows 10 Od: vini2003Wysłano: piątek, 25 września 2020 22:23Do: Mixinors/AstromineDW: SauceOfficial; AuthorTemat: Re: [Mixinors/Astromine] Creative Tank fluid type cannot be changed (#288) Unsure what you meant by filling the rocket up with fluid storage blocks, however, it is meant to be filled by hand with Canisters or Buckets in its GUI.Creative Tank issue has been solved.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
