### ISSUE TITLE
Electric Smelter resets progress

### ISSUE THREAD

**Issue by angelnc1989** [Chainmail-Studios/Astromine#291]
MC 1.16.2
Fabric 0.9.3+build.207
Astromine 1.10.6

I have a Triturator set up to auto output into an Electric Smelter.
Everytime the Triturator puts the next item into the Eletric Smelter the progress bar resets. 
The Electric Smelter basically only processes when its input is full.

**Comment by Shnupbups** [comment]
Can't reproduce, could you provide more details? A full mod list?

**Comment by Shnupbups** [comment]
Can't reproduce, could you provide more details? A full mod list?

**Comment by Astr0nii** [comment]
It happens with all machines that accept items if you shift-click an item, put an item in via a machine or insert it manually into the machine it resets the progress bar. Taking out items also does the same thing. 🤔 

MC 1.16.3
Fabric 0.9.3+build.207
Astromine 1.10.7

Mods:
Astromine
Fabric Api
Diggus Maximus
CaN i MiNe ThIs?
Advancements enlarger
Hwyla
Megane
SimpleHarvest
Inventory Sorting
ItemScroller
malilib
Roughly Enough Items
Roughly Enough Resources
Xaeros minimap

**Comment by justastranger** [comment]
Can vouch for the progress bar resetting when shift-clicking on an item stack in the electric furnace GUI. In addition, if there's any item in the slot, shift clicking will fail even when you try to add an item that would stack with it correctly (2 partial stacks that add to 1 full stack).

**Comment by lineargraph** [comment]
I think i found the issue in the smelter, but it seems like a rather common issue so I'll look for some more places before submitting a PR

**Comment by Astr0nii** [comment]
It can be abused for infinite power gen

**Comment by vini2003** [comment]
All solved.
