### ISSUE TITLE
Requested fabric version doesn't exist.

### ISSUE THREAD

**Issue by WolfSteelpaw** [Chainmail-Studios/Astromine#295]
When I try to load up the mod in 1.16.2, it says "Could not find required mod: astromine requires {fabric @ [>=0.19.0]}" and it creates an empty clause! When I try to find fabric loader 0.19.0 in my fabric installer, I can't find it at all.

**Comment by shedaniel** [comment]
Update fabric api, not fabric loader.

**Comment by WolfSteelpaw** [comment]
Thank you, the mod is no longer crashing upon startup!
