### ISSUE TITLE
Blade buttons share the same hash; shift clicking changes I/O

### ISSUE THREAD

**Issue by justastranger** [Chainmail-Studios/Astromine#297]
When changing the I/O sides for energy or items, it gets set for both. 

Astromine 1.10.7
Fabric Loader 0.9.3 build 207
Fabric API 0.21.0 build 407

**Comment by Astr0nii** [comment]
And also upgrading the machine changes its I/O

**Comment by justastranger** [comment]
Attempting to shift click items into a machine seems to sometimes change the I/O as well

**Comment by Astr0nii** [comment]
I can vouch for that happening as well. Its annoying resetting my I/O every time I do it :/

**Comment by Astr0nii** [comment]
TLDR: Shift-clicking or manually inserting items changes the I/O. Upgrading a machine changes its I/O. Power and items both share the same I/O which is annoying, devs please fix :)

**Comment by vini2003** [comment]
Unsure why shift clicking would do it, but am investigating.

**Comment by vini2003** [comment]
Should be solved.
