### ISSUE TITLE
Machines having issue with too much power input

### ISSUE THREAD

**Issue by Karpathe** [Chainmail-Studios/Astromine#300]
Example: putting a creative solar panel from tech reborn next to an electrolyzer, the electrolyzer fills up with energy and the water inside doesn't convert to hydrogen and oxygen. happens with other machines. once the solar panel is broken, the machine starts to work again. (can be replicated with other solar panels and also with Astromine solid generators and liquid generators)

Basically: When the internal energy buffer of the machine is full, it stops working. and wont work until its power source is removed.

**Comment by vini2003** [comment]
Unable to reproduce.

**Comment by vini2003** [comment]
Unable to reproduce; seems solved.

**Comment by copygirl** [comment]
Was just able to reproduce this with the Electrolyzer and Tech Reborn machines or cables. Once the machine is full of energy, it gets stuck and only breaking and placing it again causes it to start working.

**Comment by vini2003** [comment]
What version are you on?

I closed this issue thinking I'd release the dev. version same day, but voila, all sorts of real life problems happened.

**Comment by copygirl** [comment]
Astromine: `1.11.4+fabric-1.16.3`
Tech Reborn: `3.6.1+build.143`
