### ISSUE TITLE
Visual bug with liquid generator and solid generator

### ISSUE THREAD

**Issue by Karpathe** [Chainmail-Studios/Astromine#301]
Liquid generator: the arrow is in the wrong place in the gui
solid generator: with hwyla the arrow is....many arrows. 
![2020-09-23_22 31 01](https://user-images.githubusercontent.com/71393097/94098414-28fe0000-fdee-11ea-8b70-53d7ef518662.png)
![2020-09-23_22 28 21](https://user-images.githubusercontent.com/71393097/94098417-29969680-fdee-11ea-80fb-919d97005281.png)

unsure if this is a hwyla issue or a astromine issue, nothing else i can find can replicate the many arrows

**Comment by shedaniel** [comment]
We didn't add support for hwyla, an external 3rd party mod did it

**Comment by justastranger** [comment]
That mod is [Megane](https://github.com/badasintended/megane/issues)

**Comment by vini2003** [comment]
Liquid Generator issue has been fixed; reported Solid Generator HWYLA issue at Megane's repository.
