### ISSUE TITLE
Gas Canisters / Tanks can't be picked from AE2 Terminal

### ISSUE THREAD

**Issue by vini2003** [Chainmail-Studios/Astromine#302]

**Comment by lineargraph** [comment]
Maybe correlated to the issue where shiftclicking space suits leads to a desync sometimes
![screenshot](https://user-images.githubusercontent.com/20768569/94868916-67299e00-0444-11eb-8dca-6411bae828ec.png)

**Comment by vini2003** [comment]
This seems like a CCA issue, but I don't know anything else other than that it happens for now.

**Comment by vini2003** [comment]
Fixed in development build.
