### ISSUE TITLE
Astromine items / blocks not showing up.

### ISSUE THREAD

**Issue by redstonekasi** [Chainmail-Studios/Astromine#303]
Not much else to say.
Tried to see if they show up in REI but no luck.

[Log if needed](https://paste.redstonekasi.de/?75324e4519f75902#5rQP9rrYikssSj2VsRhRpbz9Wo5tYFjX5NyytSij7Jh4)

**Comment by vini2003** [comment]
Unsure what causes this; the mod is apparently loaded, could it be the JiJ issue from some time ago?

**Comment by Shnupbups** [comment]
Yep, looks like the JiJ issue, as none of the actual modules are loaded, just the wrapper for the suite.

**Comment by redstonekasi** [comment]
So how would I be able to fix this?

**Comment by justastranger** [comment]
You need to update your copy of [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3066731).

If you want to ensure that the game either loads or doesn't based on if it can load Astromine, you can extract the individual jars for the different modules to your mods folder and remove the omnibus jar.

Also, it seems that the omnibus jar only tries to require 0.19.0 while the individuals require 0.21.0. This may be causing the issues we're seeing.

**Comment by vini2003** [comment]
With updated Fabric API, this issue is solved.
