### ISSUE TITLE
Blade shift-clicking broken; Buffer sorting broken

### ISSUE THREAD

**Issue by Astr0nii** [Chainmail-Studios/Astromine#304]
The buffers are broken, Items don't stack when shift-clicking them into the buffer and buffers support inventory sorting instead it sorts your inventory taking your amour off as well. Please fix :)

**Comment by vini2003** [comment]
That's a https://github.com/vini2003/Blade issue. Sorting doesn't work because I only exposes the slot grid, not the entire inventory; and shift-clicking is a known Blade issue I haven't felt like fixing, but I might. Anyway, hope that clears it up.

**Comment by vini2003** [comment]
Shift-clicking now works, and sorting cannot be reasonably fixed without major changes to Blade.

Therefore, I have decided that you simply cannot sort Buffers.
