### ISSUE TITLE
Machines do not function when getting updated by external blocks/tile entities

### ISSUE THREAD

**Issue by DaRandom** [Chainmail-Studios/Astromine#307]
This is a major issue from what I've noticed through playing All Of Fabric 3. Machines (the ones I've tested for getting rocket fuel, as well as the Alloy Smelter) can not process a recipe if the energy input is active, items are being added/removed, receiving/sending fluids etc. 

_Note: This is a similar issue to what is described in #300, but this is regardless of power input._

They all vary slightly between each machine but the issue is still the same. The most noticeable being the Alloy Smelter in this example. I have added a few screenshots as well as a .gif to illustrate the issue.

**ALL MACHINES HAVE BEEN PROPERLY CONFIGURED!**

![2020-09-29_20 51 29](https://user-images.githubusercontent.com/23461487/94604146-8c2cde00-0297-11eb-9053-58a8d6e30015.png)
![2020-09-29_20 51 41](https://user-images.githubusercontent.com/23461487/94604150-8cc57480-0297-11eb-8190-abd5ec977ad9.png)
![2020-09-29_20 51 53](https://user-images.githubusercontent.com/23461487/94604151-8d5e0b00-0297-11eb-92cb-90e71644d1ee.png)
![2020-09-29_21-01-48](https://user-images.githubusercontent.com/23461487/94604246-ad8dca00-0297-11eb-8a7c-f5d186f457eb.gif)

**Comment by vini2003** [comment]
Item one is already fixed in development, not sure about the fluids. Thank you for the clear images!

**Comment by DaRandom** [comment]
> 
> 
> Item one is already fixed in development, not sure about the fluids. Thank you for the clear images!

I have noticed that using the mod Hwyla allows you to see the progress bar of the machines that uses the fluids in its recipe. And when it is not correctly functioning it might sometime even flash the bar at a seemingly random progress amount. Sometimes 1/3, others 2/3 etc. I wouldn't be surprised if the fluid/energy bug has a similar issue as the item progress one. Might be of help.

**Comment by vini2003** [comment]
All solved.
