### ISSUE TITLE
Energy/Items/Fluid Tabs syncronize sides when they should be seperate

### ISSUE THREAD

**Issue by DaRandom** [Chainmail-Studios/Astromine#308]
The machines, when configuring the input/output sides, keep the setup between all sides the same and do not differentiate between the type. For instance, if I want the energy input to be to the left, all other tabs also see the left side of the block as their respective input, when it really should only just be energy.

Here's a few screenshots to illustrate my point. The first screenshot shows me configuring the fluid input to the front.
![2020-09-29_20 53 36](https://user-images.githubusercontent.com/23461487/94604563-2ab93f00-0298-11eb-8dea-f0fe757351cd.png)

Here I switch to the energy tab and see the energy input is now also mysteriously on the front side of the block.
![2020-09-29_20 53 47](https://user-images.githubusercontent.com/23461487/94604566-2b51d580-0298-11eb-8dd4-c64a208ab0ae.png)

I change all energy output sides to the remaining unconfigured sides.
![2020-09-29_20 53 57](https://user-images.githubusercontent.com/23461487/94604569-2bea6c00-0298-11eb-8f1e-b734f39329d9.png)

And now all the sides on the fluid tab is also output on the same sides the energy is set to output on!
![2020-09-29_20 54 09](https://user-images.githubusercontent.com/23461487/94604572-2bea6c00-0298-11eb-8d12-773de8cb54b4.png)

**Comment by Astr0nii** [comment]
Yeah, This is happening to me also in my survival playthrough and it's annoying

**Comment by vini2003** [comment]
Duplicated of https://github.com/Mixinors/Astromine/issues/297.
