### ISSUE TITLE
Drills don't break 3x3 in creative when mining bedrock

### ISSUE THREAD

**Issue by UpcraftLP** [Chainmail-Studios/Astromine#309]
Expected: Drill mines 3x3 due to the player being in creative mode
Actual result: Only center block breaks, all others stay (see `Figure 1a`).

---

![image](https://user-images.githubusercontent.com/10714589/94681805-5550d980-0324-11eb-8a94-ff44f1a0526e.png)
**Figure 1:** Blocks to be mined; Center is bedrock.  
<br/>
<br/>

![image](https://user-images.githubusercontent.com/10714589/94681926-7dd8d380-0324-11eb-82a8-b27ef123fe9b.png)
**Figure 1a:** Blocks after breaking the center block, using an `Elite Drill` in creative mode.
<br/>

---
  
![image](https://user-images.githubusercontent.com/10714589/94681987-921cd080-0324-11eb-983b-4a959d74eb3c.png)
**Figure 2:** Blocks to be mined; Center is stone.  
<br/>
<br/>

![image](https://user-images.githubusercontent.com/10714589/94682076-b4165300-0324-11eb-8ec9-19c4befe2170.png)
**Figure 2a:** Blocks after breaking the center block using an `Elite Drill` in creative mode.

**Comment by Shnupbups** [comment]
Report to Magna

**Comment by vini2003** [comment]
Well, being more specific, https://github.com/Draylar/magna.
