### ISSUE TITLE
Disable/reduce fall damage in space

### ISSUE THREAD

**Issue by quek04** [Chainmail-Studios/Astromine#310]
I don't know if fall damage existing in space is intentional or not, but personally it kind of ruins space exploration for me. I feel like I can't go anywhere without losing half my health or dying by just jumping around. Having low gravity combined with normal fall damage feels strange, and I think fall damage should either be removed entirely when in space, or at least reduced by a large margin.

**Comment by quek04** [comment]
I'm going to try to make a PR to fix this

**Comment by quek04** [comment]
never mind, there's a weird error preventing me from doing anything lol

**Comment by Ueaj-Kerman** [comment]
should be fixed now

**Comment by vini2003** [comment]
Closed, since this has been fixed.
