### ISSUE TITLE
Spinnery related crashes on 1.16.3

### ISSUE THREAD

**Issue by LlubNek** [Chainmail-Studios/Astromine#311]
Spinnery (which is discontinued but embedded in Astromine) crashes when clicking on it in the mod list (with mod menu) and when opening the player inventory.

From mod list:
![image](https://user-images.githubusercontent.com/313762/94756839-9bc72800-0366-11eb-961b-58d62451b1e4.png)
[crash-2020-09-30_21.47.21-client.txt](https://github.com/Mixinors/Astromine/files/5309054/crash-2020-09-30_21.47.21-client.txt)
[latest.log](https://github.com/Mixinors/Astromine/files/5309055/latest.log)

From player inventory:
![image](https://user-images.githubusercontent.com/313762/94757020-1bed8d80-0367-11eb-946b-9414f2138c6d.png)
[crash-2020-09-30_21.51.14-client.txt](https://github.com/Mixinors/Astromine/files/5309065/crash-2020-09-30_21.51.14-client.txt)
[latest.log](https://github.com/Mixinors/Astromine/files/5309066/latest.log)

**Comment by shedaniel** [comment]
we don't embed spinnery anymore, it is not by us.

**Comment by LlubNek** [comment]
I see that now.  No idea which mod it is though since they apparently didn't mark the dependency in curseforge...

**Comment by LlubNek** [comment]
Found it.  It was Identity.
