### ISSUE TITLE
it says "stairs?" instead of "stars"

### ISSUE THREAD

**Issue by Redd56** [Chainmail-Studios/Astromine#318]
![image](https://user-images.githubusercontent.com/12189828/95648939-d2502180-0a8f-11eb-8c80-df3a70901328.png)
"who said 'i' wasnt among the stars"
it has an extra I in stars

**Comment by Redd56** [comment]
this is in the book

**Comment by vini2003** [comment]
This is now cannon. Space is now an infinite dimension of stairs.

**Comment by vini2003** [comment]
This is no longer cannon. Stairs have been eliminated.

**Comment by Redd56** [comment]
best issue ive ever reported lmao
