### ISSUE TITLE
Astromine crashes 1.16.2 server

### ISSUE THREAD

**Issue by ApposModding** [Chainmail-Studios/Astromine#320]
log: 11.10 08:53:44 [Server] Server thread/INFO Preparing spawn area: 0%
11.10 08:53:44 [Server] Server thread/INFO Preparing spawn area: 0%
11.10 08:53:44 [Server] Server thread/INFO Preparing spawn area: 0%
11.10 08:53:45 [Server] Server thread/INFO Time elapsed: 1312 ms
11.10 08:53:45 [Server] Startup Done (1.491s)! For help, type "help"
11.10 08:53:45 [Server] Server thread/WARN Trying to add entity with duplicated UUID a093751a-2c77-4658-9d5f-62ab4494bdaf. Existing minecraft:armor_stand#52, new: minecraft:armor_stand#53
11.10 08:53:45 [Server] Server thread/WARN Trying to add entity with duplicated UUID 291dfbec-2b7b-4c2b-9899-f665ea53af5d. Existing minecraft:armor_stand#54, new: minecraft:armor_stand#55
11.10 08:53:48 [Server] Worker-Main-8/INFO [STDERR]: Configured Feature doesn't exist at astromine:tin_ore
11.10 08:53:48 [Server] Worker-Main-19/WARN Worker-Main-19 died
11.10 08:53:48 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.class_148: Biome decoration
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163) [?:1.8.0_262]
11.10 08:53:48 [Server] INFO Caused by: net.minecraft.class_148: Biome decoration
11.10 08:53:48 [Server] INFO at net.minecraft.class_3898.method_17225(class_3898.java:579) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_262]
11.10 08:53:48 [Server] INFO ... 11 more
11.10 08:53:48 [Server] INFO Caused by: java.lang.NullPointerException: Configured Feature doesn't exist at astromine:tin_ore
11.10 08:53:48 [Server] INFO at me.shedaniel.cloth.api.dynamic.registry.v1.BiomesRegistry.lambda$registerFeature$0(BiomesRegistry.java:54) ~[4773c702-3462-4a0c-932d-18350f7bfeb9.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_1959.method_8702(class_1959.java:370) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_2794.method_12102(class_2794.java:220) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_2806.method_12151(class_2806.java:89) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-server.jar:?]
11.10 08:53:48 [Server] INFO at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-server.jar:?]
11.10 08:53:49 [Multicraft] Server shut down (running)
11.10 08:53:49 [Multicraft] Not restarting crashed server.
11.10 08:53:49 [Multicraft] Looks like a crash, check the server console. Return value: 255
11.10 08:53:49 [Multicraft] Server stopped
basicly STRIDDR is not axepting astroid ores.

**Comment by shedaniel** [comment]
Please send the whole log, and the modlist

**Comment by vini2003** [comment]
Seems you're using a 1.16.3 build in 1.16.2. Either way, I doubt we'll be getting more details - closing for now.
