### ISSUE TITLE
[1.16.3] Astromine is not registering configuredfeatures

### ISSUE THREAD

**Issue by TelepathicGrunt** [Chainmail-Studios/Astromine#329]
Hello! I was helping someone out with their collection of mods and tried it with [DebugWorldgenIssues ](https://github.com/shartte/DebugWorldGenIssues/releases/tag/v1.2.0) mod. What it found was that astromine does not register their ConfiguredFeatures. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95884310-f048ab00-0d49-11eb-9d84-569f528e4daf.png)

Specifically, when you call .configure on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init. 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/588ede281d77cd8603cb4126ef5fbbfebcaf5b86/src/main/java/com/telepathicgrunt/repurposedstructures/RSConfiguredFeatures.java#L193-L195

I hope this helps!

![image](https://user-images.githubusercontent.com/40846040/95884357-fccd0380-0d49-11eb-8ccc-b9bbe5100ad1.png)

**Comment by shedaniel** [comment]
The error of `Configured Feature doesn't exist at` error is added by Cloth, it means that the feature isn't yet registered by the data pack, there are a few possibilities here:
1. The validation check is done too early.
2. The configured feature was never registered by vanilla's registry ops

**Comment by TelepathicGrunt** [comment]
Ah I forgot about cloth. I recall gimp talking about that. Though I am not sure if he fixed DebugWorldgenIssues to bypass the cloth issue or not.

**Comment by shedaniel** [comment]
I tested with astromine and ae2, which both add ores, they both generate and there were no errors in the logs.

**Comment by shedaniel** [comment]
I think cloth's implementation is safe.

**Comment by TelepathicGrunt** [comment]
I just tried Astromine with a datapack with 1 biome that uses custom configuredfeature ores and it is spewing errors in the logs. Cloth's implementation might not be right. Furthermore, the biome was not spawning the ores at all either. There was also a bit of unknown biome id spam too in the log which is super weird but that would be an entirely different issue with astromine/datapack compat I think

Log: https://hatebin.com/wlseinamwt

Datapack (when creating a new world, click datapack, put this in, and then change the worldtype to single biome and select vanilladim:badlands): 
[vanilladim.zip](https://github.com/Mixinors/Astromine/files/5373175/vanilladim.zip)

Edit it might be me on my end. Sorry. I'll test more and see if I can make a better datapack for this

**Comment by shedaniel** [comment]
Thanks, I am able to reproduce

**Comment by shedaniel** [comment]
EDIT: Actually no, that's a different thing

**Comment by vini2003** [comment]
Any progress on this?

**Comment by shedaniel** [comment]
Fixed in development versions of astromine
