### ISSUE TITLE
Ele trolcyzer Brokne

### ISSUE THREAD

**Issue by Neubulae** [Chainmail-Studios/Astromine#331]
If a thing is constantly outputting liquid to the lyzer it ceases to lyze. doubel irrtit

**Comment by shedaniel** [comment]
are you speaking english

**Comment by Neubulae** [comment]
mine eENglsish not GOOnd Plzaese forgeiv my bAD enSSLIGH

**Comment by shedaniel** [comment]
then speak chninese

**Comment by Neubulae** [comment]
Best issue I've opened ever :tiny_potato:

**Comment by vini2003** [comment]
whatever the hell this was is probably fixed
