### ISSUE TITLE
Stacc breaks Astromine recipes

### ISSUE THREAD

**Issue by LiviiYS** [Chainmail-Studios/Astromine#333]
unable to get ingots 
![2020-10-14_20 37 30](https://user-images.githubusercontent.com/72738254/95975064-40646200-0e5d-11eb-9cf4-74b05576d4c9.png)
![2020-10-14_20 38 00](https://user-images.githubusercontent.com/72738254/95975074-435f5280-0e5d-11eb-9153-ab8555fd8678.png)

Edit: I will attach a log from the last time playing, it might help
[latest.log](https://github.com/Mixinors/Astromine/files/5377398/latest.log)

**Comment by Neubulae** [comment]
you probably have used an old version of Fabric API, please update it first

**Comment by LiviiYS** [comment]
![fabric](https://user-images.githubusercontent.com/72738254/95980640-ff704b80-0e64-11eb-832c-745ded5ee414.PNG)
im using the latest fabric api

**Comment by Ueaj-Kerman** [comment]
stacc mod is discontinued, stacc is now just an API
