### ISSUE TITLE
Oil appearing as water when using Sodium

### ISSUE THREAD

**Issue by Redd56** [Chainmail-Studios/Astromine#334]
![image](https://user-images.githubusercontent.com/12189828/96083505-1ec1a580-0e72-11eb-9034-63ce99c2c08e.png)
this is oil. or is supposed to be, it generated in an underwater cave and doesnt quite look like oil. tested and all works fine without sodium, with sodium this hapens

**Comment by justastranger** [comment]
Sodium is currently incompatible with the Fabric Rendering API. They aim to implement it in the future, but at the moment the only way to avoid these bugs is to not use Sodium.

Canvas, on the other hand, provides modest improvements, some shaders, and full compatibility with the fabric rendering API.

**Comment by vini2003** [comment]
I'm betting this 'in the future' is like our time for 'adding other planets'. So, uh, how do we avoid this?

**Comment by shedaniel** [comment]
We don't.

**Comment by vini2003** [comment]
Great.

**Comment by Redd56** [comment]
thank you sodium, another mod oofed by the lack of support for the fabric rendering api.

**Comment by vini2003** [comment]
Am I right in assumming this will never be fixed?

**Comment by shedaniel** [comment]
Please install Indium, it adds fabric rendering api support to sodium
