### ISSUE TITLE
Rocket and Tank

### ISSUE THREAD

**Issue by Romz24** [Chainmail-Studios/Astromine#337]
When you try to pour any liquid into a rocket or tank, the game crashes with an error. After that, when I try to open the gui, the error is repeated.
I pour the liquid using a bucket, the problem is observed in a single game on the server, I have not tested it.

Mod version: 1.11.4
Fabric version: 0.24.0+build.411

[crash-2020-10-20_07.10.26-client.txt](https://github.com/Mixinors/Astromine/files/5406417/crash-2020-10-20_07.10.26-client.txt)

**Comment by vini2003** [comment]
Unable to reproduce in latest development version, which should be released later today.

**Comment by vini2003** [comment]
Well, actually- this may be trickier.

**Comment by vini2003** [comment]
I suppose this is no longer happening. It's been six months, after all.
