### ISSUE TITLE
Spacesuit Chestplate Crash

### ISSUE THREAD

**Issue by TheCoolestPaul** [Chainmail-Studios/Astromine#338]
When trying to figure out how to fill the chest plate, I placed it in the anvil and it crashed the game this [this log](https://paste.ee/p/xfc6u). I've also noticed that shift+click to move the chest plate creates client sided duplicates of the plate. It'll appear in one inventory and not the other and vise versa.

**Comment by copygirl** [comment]
Trying to enchant a set of space suits, also running into this issue.
Here's my log in case it helps: https://paste.ee/p/2neM7

This issue was tagged as "other mods". How come? Is it Cardinal Components' fault?

**Comment by vini2003** [comment]
Indeed, it is CCA's fault.

**Comment by vini2003** [comment]
We have reported it to Pyrofab.

**Comment by Pyrofab** [comment]
It is in fact (mostly) not CCA's fault 😎

**Comment by vini2003** [comment]
Of course it is CCA's fault, knew it. /s

**Comment by vini2003** [comment]
Solved in development version. Will be released today if nothing goes catastrophically wrong.
