### ISSUE TITLE
Astromine crashes on launch

### ISSUE THREAD

**Issue by f-raZ0R** [Chainmail-Studios/Astromine#344]
https://pastebin.com/Nc5cifWP
might be a mod conflict issue, crashlog doesn't give enough information to tell
modlist based on internal ids:
                angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bedrockwaters: BedrockWaters 1.4.1+1.16.2
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		blade: Blade 2.0.0
		byg: BYG 1.0.14
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-block: Cardinal Components API (blocks) 2.6.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-level: Cardinal Components API (world saves) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		carvedmelons: Carved Melons 1.2.2
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1
		chains: Chains-Link 1.16.2-2.0.1
		charm: Charm 2.0.3
		cinderscapes: Cinderscapes 1.2.2+build.35-1.16.3
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.2
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_github_nathanpb_safer: Safer 1.1.0
		com_typesafe_config: config 1.4.0
		dawn: Dawn API 1.4
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta5
		extraalchemy: Extra Alchemy 1.3.0
		fabriblocks: FabriBlocks 1.2.1
		fabric: Fabric API 0.24.2+build.413-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.1+a4467d2a95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.5+build.213
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		greater_eye: Greater Eye of Ender 1.1.2
		inca: Inca 1.2.3
		jankson: Jankson 3.0.1+j1.2.0
		ktdatataglib: KtDataTagLib 1.4.0
		libblockattributes_core: LibBlockAttributes (Core) 0.8.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2
		libblockattributes_items: LibBlockAttributes (Items) 0.8.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		lithium: Lithium 0.5.6
		maelstrom_library: Maelstrom Library 0.4.1
		magna: Magna 1.4.3-1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.3
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
		morepaths: More Paths 0.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		patchouli: Patchouli 1.16.2-44-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		repurposed_structures: Repurposed Structures 1.16.3-1.6.9
		roughlyenoughitems: Roughly Enough Items 5.6.2
		roughlyenoughitems-api: REI (API) 5.6.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.2
		roughlyenoughitems-runtime: REI (Runtime) 5.6.2
		roughlyenoughresources: Roughly Enough Resources 2.1.2
		sandwichable: Sandwichable 1.1.2
		shapes: Shapes 2.0.0+build.10
		sodium: Sodium 0.1.0
		team_reborn_energy: Energy 0.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 0.1.1-SNAPSHOT
		terraform-legacy-v0: Terraform Legacy (v0) 0.1.1-SNAPSHOT
		terraform-overworld-biome-extensions-v1: Terraform Overworld Biome Extensions (v1) 0.1.1-SNAPSHOT
		terraform-shapes-api-v1: Terraform Shapes API (v1) 0.1.0-SNAPSHOT
		terrestria: Terrestria 2.1.2+build.24
		the_bumblezone: The Bumblezone - Fabric 1.16.3-2.2.8
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torridvision: Torrid Vision 0.0.3
		traverse: Traverse 3.0.0-beta+build.4
		voyager: Voyager 1.0.0
		woods_and_mires: Woods and Mires 1.0.2+1.16.3
		wrenchable: Wrenchable 1.0.0+1.16.1

**Comment by shedaniel** [comment]
we love fabric api

**Comment by shedaniel** [comment]
fixed in latest fabric api
