### ISSUE TITLE
Fluid API

### ISSUE THREAD

**Issue by irunatbullets** [Chainmail-Studios/Astromine#345]
This is probably a lot of work, so please feel free to delete, but I was wondering if it's possible to make Astromine use the same fluid API as Kibe, Indrev and AE2 for increased compatibility?

**Comment by Neubulae** [comment]
> Wait, it's all compatible?
> Always has been.

**Comment by Lionexx** [comment]
> > Wait, it's all compatible?
> > Always has been.

As of, right now, Astromine and Kibe do not work together, on my server we are running

astromine-1.11.4+fabric-1.16.3.jar
and 
kibe-1.16.3-1.4.3-BETA.jar

You can use entangled tanks/buckets and Kibe tanks with fluid from Astromine, such as oil, the oil will go in the tank, but you can't retrieve the fluid from kibe tanks(other fluids such as water work as it should) You can also not use Kibe Fluid hoppers on Astromine machines to input fluid from Kibe to Astromine, and you cannot connect Astromine fluid cables to Kibe tanks/entangled tanks, and finally you cannot input fluids from Kibe Entangled Bucket to Astromine tanks and such, as you can with normal minecraft buckets.

Edit: I have not done in-depth testing with AE2 and Astromine.

**Comment by irunatbullets** [comment]
Sorry if I came across as rude. I realise that there is limited interaction between the mods I mentioned regarding fluid anyway. I guess another way to solve it is if I approach the kibe dev to see if they could add the ability to push/pull fluids to Astromine with the fluid hopper, but I'm not really sure if that's even doable.

Edit: just clarifying what I meant about approaching the kibe dev

**Comment by Lionexx** [comment]
> Sorry if I came across as rude. I realise that there is limited interaction between the mods I mentioned regarding fluid anyway, I guess another way to solve it is if I approach the kibe Dec to see if they could push/pull fluids to Astromine with the fluid hopper, but I'm not really sure if that's even doable.

It's not possible, Astromine and Kibe just do not work together very well, as of right now. Since my last post, we updated to the latest version of Kibe but still same issues persist

**Comment by shedaniel** [comment]
Astromine hooks into LBA into supporting our fluid api, it is compatible with mods using LBA.

**Comment by vini2003** [comment]
Oh lord, waking up to a Fluid API issue. Kibe at least *includes* LBA:

```groovy
modImplementation("alexiil.mc.lib:libblockattributes-fluids:${project.lba_version}")
include("alexiil.mc.lib:libblockattributes-fluids:${project.lba_version}")
```

Which means it *should* work; clearly doesn't I suppose. Oh well I'll get around to it some time.

**Comment by Lionexx** [comment]
Thank you for the replies, looking forward to a solution.

**Comment by vini2003** [comment]
I've massively improved our LBA compatibility; will test with Kibe now.

**Comment by eehunter** [comment]
I found that the Elite Tank can extract steam from a Modern Industrialization Steel Boiler, but can't seem to interact with MI Fluid Pipes, Kibe Tanks (which the aforementioned pipes can interact with properly), or a MI Steel Macerator. I'm using Astromine: Complete 1.11.5, Kibe 1.6.7-BETA, and Modern Industrialization 0.3.16. Other mods are present, so I should probably test those three in isolation to see if any other mods' mixins are causing any issues.

**Comment by eehunter** [comment]
It should also be noted that MI pipes appear to connect, but do not transfer fluid.

**Comment by eehunter** [comment]
Correction: MI pipes can connect, but only work correctly if the side of the tank they are connected to is set to I/O mode. They will not connect if it is on the default setting, and the Output mode causes fluid to sometimes be deleted (trying to insert stuff into the tank when it's on output mode), and withdrawing from the tank seems to work even if it's on Input mode.

**Comment by Ueaj-Kerman** [comment]
MI uses it's own flapi

**Comment by Technici4n** [comment]
Just fix your LBA compat...

**Comment by Ueaj-Kerman** [comment]
it works i think idk

**Comment by Technici4n** [comment]
The issue say it doesn't... MI releases are using LBA directly. (custom API is not yet released)

**Comment by Ueaj-Kerman** [comment]
oh

**Comment by Ueaj-Kerman** [comment]
working as intended /s

**Comment by vini2003** [comment]
I do not feel like dealing with LBA.
