### ISSUE TITLE
[1.16.3] Astromine causes fire from touching lava to last for 17 minutes

### ISSUE THREAD

**Issue by Eir-nya** [Chainmail-Studios/Astromine#353]
Having Astromine installed causes the player to stay on fire after touching lava for 1024 seconds, or 17 minutes.

Steps to reproduce:

1. Install `astromine-1.11.4+fabric-1.16.3` on an instance of Minecraft 1.16.3 with Fabric
2. Create a new creative mode, commands-enabled world to test with (I used a superflat world and disabled mob spawning)
3. Place lava in the world and switch to survival mode
4. Run `/effect give @p minecraft:fire_resistance 1084 0` to give yourself 18:04 of fire resistance
5. Step in the lava and back out
6. Wait for 17:04. The fire should extinguish at approximately 1 minute of fire resistance remaining

I got the number 1024 from [here](https://github.com/Mixinors/Astromine/blob/0c3ddaad1a307fe71cc7a21bd091345579c37742/astromine-foundations/src/main/java/com/github/chainmailstudios/astromine/foundations/registry/AstromineFoundationsFluidEffects.java#L35). It appears to be the root cause of this.

Mods used in this test:
* astromine-1.11.4+fabric-1.16.3.jar
* Cardinal-Components-API-2.7.4.jar
* fabric-api-0.25.4+1.16.jar
* fabric-carpet-1.16.3-1.4.12+v201001.jar
* libblockattributes-all-0.8.2.jar
* TechReborn-1.16-3.7.1+build.162.jar

**Comment by vini2003** [comment]
Solved.

**Comment by itsNordLord** [comment]
I am still getting this error on `astromine-1.11.5+fabric-1.16.5.jar`.

This issue was posted in November, the most recent update was posted in `January`, which does not cite this issue in its changelog.
Prior updates were in October, before this issue was posted in Github.

**Comment by vini2003** [comment]
Fixed in development build - this time, apparently, for real.

**Comment by vini2003** [comment]
Closed, since this been been fixed.
