### ISSUE TITLE
Astromine: Rocket experienced rapid unscheduled disassembly: no fuel loaded

### ISSUE THREAD

**Issue by samsonong** [Chainmail-Studios/Astromine#355]
Hi there

I've crafted the Rocket and loaded it with rocket fuel, and once I pressed "Launch" other players in the server would see the following message: "Rocket experienced rapid unscheduled disassembly: no fuel loaded".

When the rocket fly past 1024 (which then I was sent to the moon), the same message appears for me and the rocket explodes.

May I check if this is a feature or there is an existing bug for the mod?

I'm using astromine-1.10.7 with fabric-1.16.3

**Comment by vini2003** [comment]
This is a known issue in that version - update to our 1.16.4 builds for a fix.
