### ISSUE TITLE
Placing a Creative Capacitor on top of a Vent makes the world unplayable.

### ISSUE THREAD

**Issue by Alucaius** [Chainmail-Studios/Astromine#366]
The issue happens only when you place a Creative Capacitor and not the other types, on top of a vent. Right after you place it your game freezes, and then crashes. If you try to join the world afterwards, it crashes again. Haven't tested it with other blocks yet. (Except for the Wire Mill which it doesn't crash)

Astromine Version: 1.12.0
Fabric API Version: 0.24.0-build411
Fabric Loader Version: 0.10.8

[crash-2020-11-26_12.55.35-server.txt](https://github.com/Mixinors/Astromine/files/5602031/crash-2020-11-26_12.55.35-server.txt)

**Comment by shedaniel** [comment]
1.12.0 is broken, please downgrade
