### ISSUE TITLE
triturator vanishing items and other oddities..

### ISSUE THREAD

**Issue by superon** [Chainmail-Studios/Astromine#367]
using astromine-1.12.0+fabric-1.16.4 in a modpack and experiencing some oddness some i suppose not intended some i'm not so sure about.
firstly a quick q. is the initial wire recipe supposed to use a complete set of shears for each wire?

ok now for things i suppose aren't supposed to happen (at least from my pov).
the primitive solid generator appears to occasionally get stuck not using energy or complete at full integer thingy power after "using" coal and being stuck at 100% and placing another piece of coal in the thing.

more worried about the triturator using resources but outputting nothing, spent an age gathering enough ancient debris for plans only to have half of them vanish in the triturator.
also found all lead vanishes from it after receiving a full stack, seems like it outputs a stack then just gives up for that particular resource:/

i tried picking it up to "reset" the machine noting it has 8 nbt tags but seems like there's no way to reset these as i behaved exactly the same after replacing

**Comment by shedaniel** [comment]
Fixed in dev, 1.12.0 is broken, downgrade
