### ISSUE TITLE
Compatibility issue: croptopia and Astromine

### ISSUE THREAD

**Issue by cooke-cookie-co** [Chainmail-Studios/Astromine#370]
Compatibility issue:
Croptopia-1.0.5-1.16.X-FABRIC.jar and astromine-1.11.4+fabric-1.16.3.jar

Creative menu not displaying vanilla blocks and items

This issue does not exist when only astromine is installed, and regardless of other mods installed

**Comment by RDKRACZ** [comment]
That's because You are using outdated Astromine...

**Comment by K0-RR** [comment]
That's because you are using an outdated Astromine. Wait what? Where did 1.12.0 version go?

**Comment by K0-RR** [comment]
If you want a temporary fix just download newer versions of cardinal components - base, block, chunk, entity, item, level, util, world.

**Comment by K0-RR** [comment]
Or this - https://easyupload.io/jq47ej

**Comment by cooke-cookie-co** [comment]
Yes, I fixed it by downloading Roughly Enough Items. I figured the developers would find this information helpful anyways.

**Comment by K0-RR** [comment]
This should be closed.
