### ISSUE TITLE
Crashing when Aurora Crystals (Better End) are used on a Conveyor (Astromine)

### ISSUE THREAD

**Issue by maradotwebp** [Chainmail-Studios/Astromine#372]
The game crashes when loading chunks in which aurora crystals from Better End are placed on a conveyor. The exception seems to occur when rendering the block entity, and I think it's more likely the issue is on your end than Better End's.

**Log**:
- [https://paste.ee/p/uVpIa](https://paste.ee/p/uVpIa)

**To reproduce:**
- Create a minecraft 1.16.4 instance with version 0.10.8 of the fabric loader
- Install [*astromine-1.11.4+fabric-1.16.3*](https://www.curseforge.com/minecraft/mc-mods/astromine-main/files/3080150), [*better-end-0.8.0-beta*](https://www.curseforge.com/minecraft/mc-mods/betterend/files/3138832), [*fabric-api-0.28.3+1.16*](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3141112) and [*fermion-mc116-2.9.217*](https://www.curseforge.com/minecraft/mc-mods/fermion/files/3142421)
- Create a new singleplayer world
- Throw down an Aurora Crystal (the block) on a Conveyor
- Watch Minecraft crash

I'd appreciate if this issue would be resolved quickly. I'm an admin on a Fabric server and this issue is occuring in a spawn chunk.

**Comment by maradotwebp** [comment]
Problem is occuring when rendering an item on the Conveyor. The specific line is here: https://github.com/Mixinors/Astromine/blob/61f4a4b127a2bbcf6d234f689e00b2f54a71e352/astromine-transportations/src/main/java/com/github/chainmailstudios/astromine/transportations/client/render/block/ConveyorRenderer.java#L162

`AuroraCrystalBlock` from Better End is defined as such:
https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/blocks/AuroraCrystalBlock.java

I'm not familiar enough with Fabric rendering to know if the issue is on your side or Better End's, sorry.

**Comment by ZenithAstralis** [comment]
So I have both these mods on MC 1.16.5, with Fabric Loader 11.2, and the crystals move perfectly, even with inserters, etc. Update if you can I suppose.

**Comment by vini2003** [comment]
I'm guessing this is fixed.
