### ISSUE TITLE
i cant find something

### ISSUE THREAD

**Issue by k3nw4y** [Chainmail-Studios/Astromine#374]
i cant find the #weebstuff in mixinors discord 
![image](https://user-images.githubusercontent.com/46229190/103140067-51a4d700-4708-11eb-9caf-98d2ea4f29e8.png)

**Comment by shedaniel** [comment]
look closer, maybe grab a microscope, usually it is reserved for people with 200 IQ brains, mere mortals might have a hard time finding it.

**Comment by Ueaj-Kerman** [comment]
did you delete it? based

**Comment by k3nw4y** [comment]
no, its not public 
![image](https://user-images.githubusercontent.com/46229190/103288939-06dad600-4a0c-11eb-8994-9f17f37fb6f6.png)

**Comment by Ueaj-Kerman** [comment]
Ir
