### ISSUE TITLE
Liquids fill up both slots in the fluid mixer

### ISSUE THREAD

**Issue by Wielmo** [Chainmail-Studios/Astromine#376]
![image](https://user-images.githubusercontent.com/76744241/103299739-82815680-49fd-11eb-9c8a-71075a990cad.png)
Tried inputting from every side, it keeps doing this, also tested in creative with different tanks and mixers and it keeps doing this.

**Comment by broman** [comment]
Can repro. Is there any viable solution for this? I know this repo isn't maintained, but hopefully this can be looked at as it is prevalant in a big mod pack.

**Comment by johannesmateboer** [comment]
Had the same problem. Created an update and a pull-request. Attached is my version of Astromine which should resolve this problem.  https://mega.nz/file/Jq4gCSbR#THmK0gw73YTCEvTX_K_XLGi9w1-4n3uzT5yzK65mqY0

**Comment by vini2003** [comment]
Closed, since this been been fixed.
