### ISSUE TITLE
Game crashes often when pressing CTRL or SHIFT

### ISSUE THREAD

**Issue by linzexin022** [Chainmail-Studios/Astromine#380]
Hi there, I found my game crashes easily when pressing CTRL or SHIFT. Here's the crash report with only Fabric API and Astromine.

It is worth mentioning that I am a Chinese player, so I need to **switch the input method** to English every time I enter the game

Game Version: 1.16.4
Astromine version: 1.12.0
Fabric API version: 0.29.0

[crash-2020-12-31_23.32.47-client.txt](https://github.com/Mixinors/Astromine/files/5757617/crash-2020-12-31_23.32.47-client.txt)

**Comment by CodedWithInsulin** [comment]
still crashing i tryed update all of my mods with current version:

i have:
Game version 1.16.4
Astromine (complete) version: 1.11.4
Fabric API: 0.29.1+1.16

even when i am in main menu or othet tab when i hit SHIFT or CONTROL in whatever combination its crashing instant.
and gisve the same crash log (but with diffrent mods) but when i disable this mod it works normaliy again

hompfully its get fix or any rply soon ;)
this is my crash log tho if he needs someting else just ask <3

[crash-2021-01-03_14.48.02-client.txt](https://github.com/Mixinors/Astromine/files/5761682/crash-2021-01-03_14.48.02-client.txt)


-- insulin

**Comment by Romz24** [comment]
I confirm I have the same crash problem.
