### ISSUE TITLE
Its not FORGE

### ISSUE THREAD

**Issue by Mystic-rgb** [Chainmail-Studios/Astromine#384]
I understand it takes lots of time and effort but is there at least an estimated time for forge Astromine

**Comment by ProjectET** [comment]
There will be no Astromine for forge. All development of this mod has been ceased for the foreseeable future until someone else wants to work on this mod. Besides this mod's license is MIT you can port it if you really want Astromine on forge. Even then there are already tech mods like Mekanism and Galacticraft on forge that do the same thing as Astromine, I really don't think forge needs a port of this mod. What you should really be doing is asking for fabric ports on forge mods.

**Comment by Shnupbups** [comment]
Not an issue. Please only use the issue tab to report issues with the mod or suggest changes or new features. Port requests are not tolerated. As @ProjectET said, if you want it for Forge, port it yourself.
