### ISSUE TITLE
Stronghold in Space

### ISSUE THREAD

**Issue by TuotHash** [Chainmail-Studios/Astromine#385]
I found a Stronghold in Space.
It didnt have any chests in the spots where lootchests wouldve spawned but there was a silverfish spawner in the stronghold and an End Portal.
I havent found any issue/report of that and i think strongholds dont belong to Space.
I am playing AOF 3 Version 2.5.7 Its not the newest Version but since i didnt see any report about this I was pretty sure this bug would be still present, because the version i am playing on is pretty new still.
Astromine Version: 1.11.4
DC: TuotHash#0377
![2021-01-28_15 42 56](https://user-images.githubusercontent.com/78159339/106155603-26872a80-6181-11eb-9fc6-ec3aef1f7f07.png)

**Comment by Ueaj-Kerman** [comment]
it's a feature now

**Comment by TuotHash** [comment]
Also I found the Stronghold before I found Galaxium.

**Comment by TuotHash** [comment]
WTF really?

**Comment by Ueaj-Kerman** [comment]
yea why not

**Comment by Ueaj-Kerman** [comment]
space stronghold pog

**Comment by TuotHash** [comment]
Why deleting the chests then?

**Comment by TuotHash** [comment]
And leaving it completely Vanilla?

**Comment by Ueaj-Kerman** [comment]
idk about that, might be a bug but lazy, I think it looks cool tbh

**Comment by TuotHash** [comment]
Its a little frustrating finding a Stronghold before Galaxium

**Comment by Ueaj-Kerman** [comment]
RNG is fun tm

**Comment by TuotHash** [comment]
Also in AOF 3 u can go to space and look for stuff there without Oxygen tanks

**Comment by TuotHash** [comment]
So this ticket can be closed now?
