### ISSUE TITLE
bruv add wiki please

### ISSUE THREAD

**Issue by dvult** [Chainmail-Studios/Astromine#387]
bruv add wiki please i like big mods but i like big mods with wiki more pls pls

**Comment by shedaniel** [comment]
bruv

**Comment by dvult** [comment]
bruv

**Comment by dvult** [comment]
add wiki or i'll do something brunvo mars

**Comment by dvult** [comment]
bruvo mars

**Comment by dvult** [comment]
bruvochael jackson
bruvtin bruveiber
bruvaniel lol nub skrub the bruvaniel 

needless to say, add wiki bruv
