### ISSUE TITLE
Sun has a giant black box around it, impossible to change.

### ISSUE THREAD

**Issue by Furiousky** [Chainmail-Studios/Astromine#392]
![image](https://user-images.githubusercontent.com/79130677/108024252-12448980-6fd9-11eb-87c9-caf5368de82e.png)

**Comment by oOHiyoriOo** [comment]
i actually somehow fixxed it, gonna take a look into that and tell you when u know how!

**Comment by Furiousky** [comment]
Thanks, let me know as soon as you can :)

**Comment by Furiousky** [comment]
did you figure it out?

**Comment by ProjectET** [comment]
Its caused by optifine.

**Comment by Furiousky** [comment]
> Its caused by optifine.

How can I fix it?

**Comment by ProjectET** [comment]
use a different shader like sildurs vibrant

**Comment by oOHiyoriOo** [comment]
He's right, sry i didnt told you earlier, i was busy.
But using another shader is fixxing the issue.

**Comment by shedaniel** [comment]
Shaders support are not guaranteed! You are on your own!￼
