### ISSUE TITLE
Block breaker ticking block entity crash

### ISSUE THREAD

**Issue by saltyseadoggo** [Chainmail-Studios/Astromine#393]
Greetings. I made a simple cobblestone generator using a block breaker to collect the cobblestone (*technically,* it was a dirt generator using *Earth2Java* mud, but the concept is the same), and everything was working well until I configured the block breaker to unload its items into an adjacent *[Blockus](https://github.com/Brandcraf06/Blockus)* birch barrel. At this point, the world became entirely unplayable, as I cannot be in it for more than a few seconds before the game crashes with a ticking block entity error.

Crash report: 
[crash-2021-02-20_01.27.57-server.txt](https://github.com/Mixinors/Astromine/files/6014550/crash-2021-02-20_01.27.57-server.txt)
*Astromine* version: 1.11.5
Fabric API version: 0.30.0
Fabric loader version: 0.11.1
Minecraft version: 1.16.5

Aside from this, I have tried removing the tile entity with NBTExplorer, only for it to regenerate immediately upon starting the world again. If anyone has any advice for how I can stop the crashing and get back to playing in this world, I would greatly appreciate it, as I do not want to lose it.

**Comment by saltyseadoggo** [comment]
Further testing has revealed this issue to be a conflict between this mod and Age of Exile. Having only them and their dependencies in the mods folder, the crash can be reproduced by simply building a cobblestone generator that uses a block breaker connected to an adjacent advanced solid generator with fuel inside of it, and a vanilla barrel also adjacent to it that the block breaker is configured to send the cobblestone into.

**Comment by shedaniel** [comment]
https://github.com/Siphalor/nbt-crafting/blob/40699829d8cd60df75777f262bea37cfb2f091b9/src/main/java/de/siphalor/nbtcrafting/mixin/MixinItemStack.java#L35

Please report to NBT Crafting.
