### ISSUE TITLE
Energy API

### ISSUE THREAD

**Issue by rmuchan** [Chainmail-Studios/Astromine#394]
Industrial Revolution: [here](https://github.com/GabrielOlvH/Industrial-Revolution)

I've observed that

- Astromine generators don't send energy to adjacent IR machines.
- Astromine cables don't connect to IR blocks.
- Astromine generators do connect to IR cables, and send energy correctly.
- IR generators/cables do send energy to adjacent Astromine machines.

Well these don't make much sense...

**Comment by Technici4n** [comment]
Yes this is because IR is now using a new energy API, which allows IR to see all other machines, but machines/cables from other mods may not "see" IR machines. The fix is to use IR cables whenever it is necessary.

**Comment by vini2003** [comment]
I do not feel like dealing with other energy APIs. We have support for TechReborn Energy, and that's it.

**Comment by Ueaj-Kerman** [comment]
based and taterpilled
