### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by K0-RR** [Chainmail-Studios/Astromine#400]
- Magna (version included in the Astromine Core is using broken clothconfig version)

**Comment by shedaniel** [comment]
Can you elaborate

**Comment by K0-RR** [comment]
Yes, I'm talking about the dependencies included in the Astromine-Core.jar (META-INF/jars/). One of them is [Magna](https://github.com/Draylar/magna) which comes with its own dependency - cloth-config.
The version (of Magna) which comes with Astromine is old, and contains old cloth-config which spits errors in the console when launching Minecraft. Nothing game-breaking.

**Comment by K0-RR** [comment]
Btw it seems like both Astromine Core and Magna contains cloth-config

There is also (in the Astronomie jar)
- Cardinal Components API v2.7.10. The newest is v2.7.13.
- LibBlockAttributes v0.8.5 - newest is v0.8.7.

**Comment by shedaniel** [comment]
Then ignore the warnings, they sre just warnings
