### ISSUE TITLE
Minecraft Crashes when I explode or launch rocket 

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#404]
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access method org.joml.Matrix4d._m30(D)Lorg/joml/Matrix4d; from class net.minecraft.class_761
Exit Code: -1 PLZ HELPP

**Comment by vini2003** [comment]
I have no idea why, how, or when this happens, but it shouldn't happen anymore.

**Comment by vini2003** [comment]
Closed, this issue is related to JOML and not caused by Astromine.
