### ISSUE TITLE
Registered modded 'astromine:asteroid_stone' as Material 'ASTROMINE_ASTEROID_STONE'

### ISSUE THREAD

**Issue by ZenithAstralis** [Chainmail-Studios/Astromine#405]
Why does it do this? It appears to cause worldedit to throw errors when attempting to use any astromine block. The command autofills "ASTROMINE_ASTEROID_STONE" but not "astromine:asteroid_stone", and the server needs to be restarted to restore functionality. 

I'm not sure if I should be tracking this to my worldedit install, or here, so I just want to know the reasoning of why it was registered under a different name, and if that's common, oor...?

**Comment by shedaniel** [comment]
Share the error

**Comment by ZenithAstralis** [comment]
It was just that in a Thread/Warn, for each material, but I removed the Cardboard mod and am no longer having issues, so I'm fairly sure it was a problem with how they implemented the item registries for bukkit
