### ISSUE TITLE
I crash when mining with the drills

### ISSUE THREAD

**Issue by RRsopa** [Chainmail-Studios/Astromine#406]
i crash when i try to mine anything with a drill from your mod.
im playing on my minecraft modpack Expanded Horizons (Fabric) if you want to see the mods or do you want a crash report?

**Comment by shedaniel** [comment]
Share the error

**Comment by RRsopa** [comment]
[crash-2021-03-17_19.20.51-client.txt](https://github.com/Mixinors/Astromine/files/6191315/crash-2021-03-17_19.20.51-client.txt)
I think it was this one, because i crashed multiple times
So, i tried switching mod versions and the initial time the world was loading i managed to drop the drill, deleted it with lava and stopped crashing.
Please tell me if you need the log or any other crash report because i have six crash reports.

**Comment by vini2003** [comment]
This is a Magna error, which has nothing of importance in the stack trace. Unable to reproduce or pinpoint.

**Comment by vini2003** [comment]
Drills are now 1x1, therefore Magna is no longer involved.
