### ISSUE TITLE
Minecraft sound event Errors:

### ISSUE THREAD

**Issue by MegaLP** [Chainmail-Studios/Astromine#407]
Registry remapping failed Received ID map for Minecraft:sound_event contains IDs unknown to the receiver!
- astromine:block.Machine.click
- astromine:block.incinerator.incinerate

**Comment by dannydinlo** [comment]
I found that if you like, you can delete the sounds.json file and it works fine. Obviously you lose sound but for the sake of keeping the mod in, could be worse. I can send the file to you if you like, feel kind of bad just straight up reuploading his work.
