### ISSUE TITLE
Electrolyzer crashes Aternos server when opened.

### ISSUE THREAD

**Issue by thebot7744** [Chainmail-Studios/Astromine#408]
The error message: 

[20:53:24] [Server thread/ERROR]: Encountered an unexpected exception
--
154 | java.lang.NoClassDefFoundError: net/minecraft/class_746
155 | at com.github.chainmailstudios.astromine.technologies.common.screenhandler.TankScreenHandler.initialize(TankScreenHandler.java:105) ~[astromine-technologies-1.11.3+fabric-1.16.3.jar:?]
156 | at com.github.vini2003.blade.common.utilities.Networks$Companion$2$1.run(Networks.java:78) ~[c0c43b0e-d277-4513-9aee-66430f32fa21.jar:?]
157 | at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
158 | at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
159 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
160 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
161 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
162 | at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
163 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
164 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
165 | at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
166 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:718) ~[intermediary-server.jar:?]
167 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
168 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
169 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
170 | Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
171 | at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
172 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
173 | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_222]
174 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
175 | at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric.jar:?]
176 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
177 | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric.jar:?]
178 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
179 | ... 15 more
180 | [20:53:24] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2021-03-27_20.53.24-server.txt

**Comment by shedaniel** [comment]
Please update astromine, report again if it is not fixed by the latest version.
