### ISSUE TITLE
Problems with catwalk and catwalk stairs 

### ISSUE THREAD

**Issue by heyjudek** [Chainmail-Studios/Astromine#410]
I'd like to make a few suggestions regarding catwalk items. 
First, some problems with Catwalks and stairs:
1) It is very easy to fall of the railings of catwalks, maybe increase their heights a little bit? One misstep and one call fall down.
2) Catwalk railings disappear when connected to another catwalk but not to stairs, shouldn't they be connecting to stairs too?
3) It is very annoying building catwalk stairs, they do not connect diagonally. So, one has to build catwalks under them and then proceed to building stairs over them. And then destroy the catwalks under them since they look very ugly.

Another suggestion I would like to make is the addition of catwalk ladder, this would greatly increase their functionality.

**Comment by Ueaj-Kerman** [comment]
added uh sidebars to the stairs n made the catblock blocks actually work

**Comment by heyjudek** [comment]
May I ask when you are planning to release this version? The latest update is still over 4 months old,

**Comment by shedaniel** [comment]
When it’s done, don’t ask.

**Comment by vini2003** [comment]
Closed, since catwalks have been removed.
