### ISSUE TITLE
Issue #353 is marked as Solved but the bug is still present

### ISSUE THREAD

**Issue by itsNordLord** [Chainmail-Studios/Astromine#411]
#353 - Lava sources ignite players for 17 minutes

[astromine-foundations/src/main/java/com/github/chainmailstudios/astromine/foundations/registry/AstromineFoundationsFluidEffects.java ](https://github.com/Mixinors/Astromine/blob/development-1.16.5/astromine-foundations/src/main/java/com/github/chainmailstudios/astromine/foundations/registry/AstromineFoundationsFluidEffects.java) was the cited file that had an error, and the error was removed, but the issue still persists.

**Comment by shedaniel** [comment]
Reopened that
