### ISSUE TITLE
[FABRIC] CRASH

### ISSUE THREAD

**Issue by Domaman202** [Chainmail-Studios/Astromine#414]
Logs - https://pastebin.com/3ZAhRAu3

Installed mods:
1. AE2AO-7.0.6
2. AE2WTLib-1.0.7-beta.1
3. appliedenergistics2-fabric-8.2.0-alpha.3
4. astromine-1.11.5+fabric-1.16.5
5. fabric-api-0.34.2+1.16
6. mechanix-3.3.0
7. nbtcrafting-2.0.11+mc1.16.4
8. optifabric-1.9.6
9. OptiFine_1.16.5_HD_U_G7
10. RebornCore-1.16-4.7.2+build.132
11. spark-fabric
12. spatialharvesters_fabric_1.16.x-0.11.7a
13. TechReborn-1.16-3.8.2+build.220

**Comment by shedaniel** [comment]
Please test without astromine to check if the issue still persists after

**Comment by Domaman202** [comment]
ok, installed i found out that schematics problems when Spark-Fabric
