### ISSUE TITLE
mixin Error?

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#417]
I've found an error in the log & will show you.
MC-Version 1.16.5

`12.06 16:39:09 [Server] main/WARN @ModifyVariable(@At("INVOKE")) Shift.BY=2 on astromine.mixins.json:BiomeLayerSamplerMixin::localvar$zmj000$modifyBiome exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.`

**Comment by vini2003** [comment]
Closed, since this been been fixed.
