### ISSUE TITLE
Astromine makes modpack crash on launch

### ISSUE THREAD

**Issue by Leomacchia** [Chainmail-Studios/Astromine#419]
I can't launch my own modpack and I really don't understand what's wrong with the mod...

[crash-2021-06-21_18.40.46-client.txt](https://github.com/Mixinors/Astromine/files/6693221/crash-2021-06-21_18.40.46-client.txt)

**Comment by AnAwesomGuy** [comment]
it's bcuz ur using astromine complete with astromine modules. remove 		
astromine-core: Astromine: Core 1.11.5+fabric-1.16.5,
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5,
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5,
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5,
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
