### ISSUE TITLE
d

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#424]
d

**Comment by SZUMASTER** [comment]
I will fix it and publish on curseforge.

**Comment by vini2003** [comment]
Good luck!

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/150097846-089934e6-9059-4cf2-a4f6-29dd104d6dd2.gif)

**Comment by ImAK9** [comment]
![5D52FBB5-C29E-418C-8F75-815085B2754E](https://user-images.githubusercontent.com/29925108/150103167-2387ee36-23b9-4039-befe-017cfb254f5c.gif)

**Comment by Shnupbups** [comment]
_'It was working and now it is not working': An erectile dysfunction tale™_

**Comment by SZUMASTER** [comment]
Of course. Look on the crash log. Dont be mad bro, maybe this time you will comeback ™
![image](https://user-images.githubusercontent.com/97899734/150265848-5e80b359-dca2-4cbe-83ca-92a7dc3d0da4.png)

I need an update via cf, the license does not indicate anything that publishing was prohibited? you have a pain in your ass but you do nothing? ; v

https://user-images.githubusercontent.com/97899734/150265890-7fff595b-137c-4de3-86a6-3b5960d29440.mp4

**Comment by shedaniel** [comment]
There is nothing preventing you from re-distributing Astromine, but just remember that we would be happy if your releases could be provided under a different name or equivalent as that could confuse users from the official releases. Of course, legally speaking you have no obligation in doing this.

The future of Astromine is unknown and we are unable to provide any details on that subject

**Comment by SZUMASTER** [comment]
Thanks for the information, I want to live in harmony, nor do I want to do
something that others will be dissatisfied with. If you find a moment you
could at least build and publish version 1.16.5 on cf, I really care about
this modification, its only ten minutes,

Thanks,
(>^-^<)

W dniu czw., 20.01.2022 o 07:13 shedaniel ***@***.***>
napisał(a):

**Comment by Neubulae** [comment]
the mod knows when it works by knowing when it workn't.

**Comment by SZUMASTER** [comment]
<img src="https://user-images.githubusercontent.com/97899734/150304323-fbc8258f-8bd2-4f08-926e-499df7784fbe.gif" width="250" height="250"> 
<img src="https://user-images.githubusercontent.com/97899734/150304333-b6f9d9ac-0d66-4df8-8eed-3a7e26f60b8d.gif" width="250" height="250"> 

<img src="https://user-images.githubusercontent.com/97899734/150304339-eadfed65-0ada-48f1-8ca9-25ae799d5fe5.gif" width="250" height="250">
