### ISSUE TITLE
[1.16.5] Invalid AW causing crash on new loader

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#425]
→ [logs](https://pastebin.com/bYKCBRg3)

**Comment by vini2003** [comment]
Are you running a custom build or a CurseForge build?

Regardless, we have ceased 1.16.5 development in favor of 1.18.1 development. I'm sorry for the inconvenience, but simply don't have the time, motivation and manpower to keep both going. Therefore, we likely won't be fixing this issue.

**Comment by ghost** [comment]
Edited:

I think changes are already implemented, it is probably enough to fix the accesswidener file according to the report title set by
shedaniel and publish release on the curseforge website.

I know you are not updating this version anymore, but I always have some hope. For this reason, I removed the modification from the modpack a long time ago, as soon as I found out about the problem related to report #416

**Comment by vini2003** [comment]
You didn't answer any of my questions, so it's a bit tough to help you.

**Comment by ghost** [comment]
Minecraft: 1.16.5,
Launcher: 0.12.12,
Curseforge release: astromine-1.11.5+fabric-1.16.5,
Fabric API: 0.42.0,

Thanks

**Comment by vini2003** [comment]
Thank you!
We won't be updating 1.16.5 further, but this issue will be fixed as soon as I've got time for it.

**Comment by SZUMASTER** [comment]
It's fixed already, just fix the accesswidener and upload the version on cf,

thanks.
