### ISSUE TITLE
Modular Astromine? 

### ISSUE THREAD

**Issue by StockiesLad** [Chainmail-Studios/Astromine#428]
Could Astromine be separated into separate modules with their own jars so that people can select what part they want (Minerals, Machines, Gear, Space)

I noticed that the machines are REALLY nice. I personally would like to have the machines + resources without the other stuff.

**Comment by shedaniel** [comment]
bruhh we tried but too much effort just hide them in kjs or something

**Comment by StockiesLad** [comment]
First, i had no idea that u worked on this mod. Thats pretty cool. Secondly, I might try it, but I’ll most likely end up just deleting everything i don't want to use in order to save ram. I have been hiding to much lol.
